In [101]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [102]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [103]:
df_train.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,...,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,...,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,Poor,No,Weekly,House,2869.0
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,...,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,Average,Yes,Monthly,House,1483.0
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,...,1.0,14.0,NaN,3.0,2023-09-30 15:21:39.221386,Good,Yes,Weekly,House,567.0
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,...,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,Poor,Yes,Daily,Apartment,765.0
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,...,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,Poor,Yes,Weekly,House,2022.0

In [104]:
df_test.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
0,1200000,28.0,Female,2310.0,NaN,4.0,Bachelor's,Self-Employed,7.657981,Rural,Basic,NaN,19.0,NaN,1.0,2023-06-04 15:21:39.245086,Poor,Yes,Weekly,House
1,1200001,31.0,Female,126031.0,Married,2.0,Master's,Self-Employed,13.381379,Suburban,Premium,NaN,14.0,372.0,8.0,2024-04-22 15:21:39.224915,Good,Yes,Rarely,Apartment
2,1200002,47.0,Female,17092.0,Divorced,0.0,PhD,Unemployed,24.354527,Urban,Comprehensive,NaN,16.0,819.0,9.0,2023-04-05 15:21:39.134960,Average,Yes,Monthly,Condo
3,1200003,28.0,Female,30424.0,Divorced,3.0,PhD,Self-Employed,5.136225,Suburban,Comprehensive,1.0,3.0,770.0,5.0,2023-10-25 15:21:39.134960,Poor,Yes,Daily,House
4,1200004,24.0,Male,10863.0,Divorced,2.0,High School,Unemployed,11.844155,Suburban,Premium,NaN,14.0,755.0,7.0,2021-11-26 15:21:39.259788,Average,No,Weekly,House

In [105]:
df_train.isna().sum()

id                           0
Age                      18705
Gender                       0
Annual Income            44949
Marital Status           18529
Number of Dependents    109672
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [106]:
df_test.isna().sum()

id                           0
Age                      12489
Gender                       0
Annual Income            29860
Marital Status           12336
Number of Dependents     73130
Education Level              0
Occupation              239125
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [107]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [108]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1181295 non-null  float64
 1   Gender                1200000 non-null  object
 2   Annual Income         1155051 non-null  float64
 3   Marital Status        1181471 non-null  object
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(9), object(11)
memory usage: 183.1+ MB

In [109]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [110]:
set(df_train['Age']).difference(set(df_test['Age']))

{nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...}

In [111]:
df_train['Age'] = df_train['Age'].fillna('None')
df_test['Age']  = df_test['Age'].fillna('None')

In [112]:
df_train['Age'] = df_train['Age'].astype(str)
df_test['Age']  = df_test['Age'].astype(str)

In [113]:
all_vals = pd.concat([
    df_train['Age'],
    df_test['Age']
])

label.fit(all_vals)

LabelEncoder()

In [114]:
df_train['Age'] = label.transform(df_train['Age'])
df_test['Age'] = label.transform(df_test['Age'])

In [115]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  object
 2   Annual Income         1155051 non-null  float64
 3   Marital Status        1181471 non-null  object
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(8), int64(1), object(11)
memory usage: 183.1+ MB

In [116]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income            44949
Marital Status           18529
Number of Dependents    109672
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [117]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [118]:
set(df_test['Gender']).difference(set(df_train['Gender']))

set()

In [119]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [120]:
df_train['Annual Income'] = df_train['Annual Income'].fillna('None')
df_test['Annual Income']  = df_test['Annual Income'].fillna('None')

In [121]:
df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status           12336
Number of Dependents     73130
Education Level              0
Occupation              239125
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [122]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  object
 2   Annual Income         1200000 non-null  object
 3   Marital Status        1181471 non-null  object
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(7), int64(1), object(12)
memory usage: 183.1+ MB

In [123]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [124]:
set(df_test['Gender']).difference(set(df_train['Gender']))

set()

In [125]:
all_vals = pd.concat([
    df_train['Gender'],
    df_test['Gender']
])

label.fit(all_vals)

LabelEncoder()

In [126]:
df_train['Gender'] = label.transform(df_train['Gender'])
df_test['Gender'] = label.transform(df_test['Gender'])

In [127]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  object
 3   Marital Status        1181471 non-null  object
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(7), int64(2), object(11)
memory usage: 183.1+ MB

In [128]:

df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status           12336
Number of Dependents     73130
Education Level              0
Occupation              239125
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [129]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [130]:
set(df_test['Annual Income']).difference(set(df_train['Annual Income']))

{65536.0,
 98304.0,
 32775.0,
 32778.0,
 12.0,
 65549.0,
 15.0,
 98324.0,
 131097.0,
 32794.0,
 131098.0,
 32797.0,
 98340.0,
 131112.0,
 131114.0,
 32811.0,
 32814.0,
 65585.0,
 32819.0,
 98358.0,
 98359.0,
 131126.0,
 32826.0,
 131133.0,
 98371.0,
 131139.0,
 131140.0,
 131143.0,
 98378.0,
 98379.0,
 32844.0,
 65615.0,
 32849.0,
 98392.0,
 131167.0,
 131170.0,
 32869.0,
 32870.0,
 98408.0,
 131176.0,
 98410.0,
 65643.0,
 32876.0,
 65646.0,
 65648.0,
 65649.0,
 32882.0,
 98418.0,
 32884.0,
 98420.0,
 65656.0,
 98428.0,
 32896.0,
 32898.0,
 131206.0,
 98443.0,
 32908.0,
 131214.0,
 32918.0,
 32919.0,
 65689.0,
 98465.0,
 98467.0,
 165.0,
 65706.0,
 32945.0,
 32948.0,
 131255.0,
 187.0,
 65724.0,
 98491.0,
 98496.0,
 32968.0,
 32969.0,
 131275.0,
 131277.0,
 32976.0,
 98513.0,
 131281.0,
 131291.0,
 98529.0,
 32997.0,
 131301.0,
 65770.0,
 65773.0,
 240.0,
 65779.0,
 131316.0,
 252.0,
 98561.0,
 33030.0,
 131336.0,
 65804.0,
 131341.0,
 131343.0,
 131355.0,
 291.0,
 65834.0,
 131370.0,
 98607.0,
 33074.0,
 33079.0,
 131384.0,
 131389.0,
 131398.0,
 330.0,
 131412.0,
 342.0,
 65879.0,
 33118.0,
 33120.0,
 65891.0,
 359.0,
 131432.0,
 361.0,
 98670.0,
 131438.0,
 98673.0,
 131443.0,
 377.0,
 379.0,
 98684.0,
 98686.0,
 33154.0,
 65924.0,
 65925.0,
 33158.0,
 98696.0,
 131464.0,
 98701.0,
 98702.0,
 131469.0,
 131471.0,
 403.0,
 65942.0,
 33183.0,
 131487.0,
 33187.0,
 131492.0,
 421.0,
 98725.0,
 430.0,
 98736.0,
 131511.0,
 131512.0,
 443.0,
 131521.0,
 33218.0,
 98756.0,
 98757.0,
 33229.0,
 33230.0,
 131545.0,
 131547.0,
 66024.0,
 66025.0,
 131560.0,
 66027.0,
 131561.0,
 66030.0,
 98806.0,
 98819.0,
 131588.0,
 66055.0,
 98826.0,
 131595.0,
 66061.0,
 33296.0,
 33298.0,
 131603.0,
 131604.0,
 66075.0,
 98843.0,
 98845.0,
 33310.0,
 33315.0,
 66088.0,
 33323.0,
 33325.0,
 66098.0,
 131639.0,
 98873.0,
 570.0,
 33339.0,
 66106.0,
 66112.0,
 33345.0,
 66114.0,
 581.0,
 33350.0,
 33355.0,
 131663.0,
 131674.0,
 131679.0,
 66144.0,
 66146.0,
 66152.0,
 33389.0,
 66161.0,
 98930.0,
 33402.0,
 33404.0,
 131708.0,
 131718.0,
 33415.0,
 131724.0,
 98959.0,
 66198.0,
 33432.0,
 98972.0,
 98977.0,
 131750.0,
 66222.0,
 66223.0,
 131760.0,
 98994.0,
 131768.0,
 99005.0,
 66239.0,
 66240.0,
 33473.0,
 66242.0,
 99019.0,
 33491.0,
 66260.0,
 99031.0,
 66268.0,
 99037.0,
 33507.0,
 33514.0,
 131820.0,
 33517.0,
 66286.0,
 66292.0,
 99062.0,
 131833.0,
 33533.0,
 131838.0,
 33535.0,
 131840.0,
 131848.0,
 33549.0,
 99095.0,
 66329.0,
 33563.0,
 33564.0,
 131868.0,
 66334.0,
 33569.0,
 66337.0,
 33574.0,
 66351.0,
 99121.0,
 66356.0,
 131896.0,
 99130.0,
 66369.0,
 131905.0,
 33605.0,
 131910.0,
 66375.0,
 131914.0,
 99147.0,
 33618.0,
 33621.0,
 66392.0,
 131932.0,
 131934.0,
 131939.0,
 131941.0,
 33642.0,
 131953.0,
 33656.0,
 33659.0,
 33661.0,
 99198.0,
 131966.0,
 33664.0,
 66434.0,
 66442.0,
 131978.0,
 131980.0,
 131982.0,
 131987.0,
 99220.0,
 66455.0,
 99231.0,
 99232.0,
 99233.0,
 99235.0,
 33702.0,
 132007.0,
 66473.0,
 132014.0,
 66479.0,
 99259.0,
 99261.0,
 99263.0,
 132035.0,
 132036.0,
 132037.0,
 132038.0,
 99272.0,
 132042.0,
 972.0,
 66508.0,
 132047.0,
 33747.0,
 99292.0,
 132062.0,
 33762.0,
 132075.0,
 132076.0,
 99315.0,
 33785.0,
 33787.0,
 33788.0,
 66559.0,
 99330.0,
 66564.0,
 99334.0,
 33802.0,
 33807.0,
 33808.0,
 66575.0,
 66576.0,
 99343.0,
 66589.0,
 132126.0,
 66592.0,
 132135.0,
 66604.0,
 99375.0,
 99381.0,
 132151.0,
 33859.0,
 33863.0,
 66632.0,
 66644.0,
 66646.0,
 66648.0,
 33886.0,
 33887.0,
 1125.0,
 99429.0,
 33895.0,
 33896.0,
 33904.0,
 66672.0,
 132215.0,
 33918.0,
 33919.0,
 132226.0,
 33930.0,
 33931.0,
 66703.0,
 99475.0,
 132243.0,
 33943.0,
 99485.0,
 33952.0,
 66721.0,
 132257.0,
 132268.0,
 99502.0,
 132272.0,
 132273.0,
 33972.0,
 33973.0,
 132276.0,
 132280.0,
 33979.0,
 33980.0,
 132288.0,
 33985.0,
 132292.0,
 33996.0,
 66767.0,
 34004.0,
 66777.0,
 99552.0,
 99553.0,
 99558.0,
 1261.0,
 99566.0,
 132338.0,
 34036.0,
 66804.0,
 132340.0,
 34042.0,
 99582.0,
 99585.0,
 34050.0,
 99586.0,
 34052.0,
 99588.0,
 132354.0,
 132356.0,
 99595.0,
 132365.0,
 34062.0,
 1295.0,
 34064.0,
 132369.0,
 99602.0,
 99605.0,
 1303.0,
 1308.0,
 66844.0,
 99612.0,
 99625.0,
 66859.0,
 132402.0,
 132404.0,
 132414.0,
 99652.0,
 34123.0,
 99668.0,
 99672.0,
 132443.0,
 99679.0,
 132450.0,
 99683.0,
 34148.0,
 132462.0,
 99698.0,
 99699.0,
 99706.0,
 132480.0,
 66949.0,
 34182.0,
 34183.0,
 66952.0,
 99719.0,
 66954.0,
 132496.0,
 132502.0,
 99737.0,
 99742.0,
 66975.0,
 1443.0,
 99761.0,
 67001.0,
 67002.0,
 1467.0,
 99769.0,
 67006.0,
 1471.0,
 67007.0,
 132544.0,
 67016.0,
 34250.0,
 99789.0,
 34258.0,
 1497.0,
 34265.0,
 34267.0,
 1503.0,
 132576.0,
 99810.0,
 99811.0,
 99817.0,
 99818.0,
 34286.0,
 1522.0,
 99829.0,
 34296.0,
 99834.0,
 34305.0,
 99843.0,
 132616.0,
 34316.0,
 132628.0,
 67098.0,
 132634.0,
 34333.0,
 34340.0,
 67109.0,
 132644.0,
 99880.0,
 67116.0,
 1587.0,
 99892.0,
 99897.0,
 99898.0,
 132667.0,
 99900.0,
 132670.0,
 1603.0,
 132678.0,
 67145.0,
 132681.0,
 34379.0,
 67151.0,
 34393.0,
 99929.0,
 99930.0,
 132698.0,
 1631.0,
 34399.0,
 132704.0,
 99938.0,
 132705.0,
 132707.0,
 67179.0,
 34417.0,
 34424.0,
 1660.0,
 34442.0,
 99978.0,
 99980.0,
 99985.0,
 132758.0,
 99994.0,
 132763.0,
 67230.0,
 132767.0,
 100000.0,
 67235.0,
 67236.0,
 100010.0,
 132781.0,
 100015.0,
 67251.0,
 100020.0,
 34490.0,
 132797.0,
 132802.0,
 1732.0,
 132806.0,
 34503.0,
 132808.0,
 34507.0,
 1743.0,
 34511.0,
 67280.0,
 132817.0,
 67286.0,
 67292.0,
 100061.0,
 34526.0,
 34527.0,
 67296.0,
 100063.0,
 67299.0,
 132835.0,
 1767.0,
 1771.0,
 67310.0,
 100079.0,
 34544.0,
 67312.0,
 67313.0,
 132853.0,
 67323.0,
 34558.0,
 132862.0,
 34561.0,
 67338.0,
 67341.0,
 34574.0,
 67345.0,
 100115.0,
 132885.0,
 132887.0,
 100120.0,
 34586.0,
 100124.0,
 132899.0,
 67369.0,
 100139.0,
 34606.0,
 132910.0,
 67376.0,
 34614.0,
 100150.0,
 100151.0,
 67385.0,
 132921.0,
 67390.0,
 67399.0,
 132936.0,
 132938.0,
 34637.0,
 34645.0,
 34650.0,
 100188.0,
 132960.0,
 67431.0,
 132973.0,
 132974.0,
 67449.0,
 100221.0,
 132991.0,
 100225.0,
 100228.0,
 67462.0,
 100232.0,
 133008.0,
 67475.0,
 100244.0,
 34718.0,
 100256.0,
 100257.0,
 133032.0,
 34731.0,
 1965.0,
 67502.0,
 67503.0,
 100273.0,
 1970.0,
 1976.0,
 133049.0,
 100284.0,
 133055.0,
 67525.0,
 133071.0,
 100316.0,
 133085.0,
 100318.0,
 100320.0,
 34786.0,
 34789.0,
 67558.0,
 133096.0,
 34804.0,
 34809.0,
 100346.0,
 34812.0,
 34813.0,
 133124.0,
 2053.0,
 67594.0,
 34833.0,
 100371.0,
 67604.0,
 34837.0,
 67607.0,
 100375.0,
 34844.0,
 100383.0,
 133153.0,
 34853.0,
 100390.0,
 100392.0,
 133165.0,
 34864.0,
 100401.0,
 34866.0,
 67638.0,
 34873.0,
 67644.0,
 67645.0,
 133191.0,
 67656.0,
 133194.0,
 67660.0,
 2125.0,
 34893.0,
 67663.0,
 67664.0,
 100428.0,
 2130.0,
 100435.0,
 2132.0,
 34901.0,
 2136.0,
 34904.0,
 67675.0,
 2141.0,
 67677.0,
 34914.0,
 133235.0,
 100469.0,
 67703.0,
 67707.0,
 67708.0,
 133246.0,
 67715.0,
 2186.0,
 2187.0,
 100503.0,
 34971.0,
 100519.0,
 133290.0,
 67755.0,
 34989.0,
 34997.0,
 67767.0,
 133305.0,
 100538.0,
 133306.0,
 35004.0,
 35005.0,
 67777.0,
 2248.0,
 67785.0,
 2253.0,
 35027.0,
 2260.0,
 35030.0,
 2266.0,
 2267.0,
 133339.0,
 100579.0,
 35047.0,
 2290.0,
 133366.0,
 2302.0,
 133374.0,
 67846.0,
 67847.0,
 35082.0,
 133390.0,
 35088.0,
 100625.0,
 100626.0,
 100628.0,
 133396.0,
 100631.0,
 35097.0,
 67867.0,
 35101.0,
 133407.0,
 35105.0,
 67877.0,
 2342.0,
 133418.0,
 67885.0,
 67887.0,
 35121.0,
 35129.0,
 35131.0,
 133435.0,
 133437.0,
 67909.0,
 133454.0,
 100687.0,
 133460.0,
 35158.0,
 100696.0,
 133465.0,
 67937.0,
 133480.0,
 133481.0,
 2416.0,
 35188.0,
 100725.0,
 100728.0,
 100729.0,
 100734.0,
 67968.0,
 67976.0,
 35209.0,
 67978.0,
 100749.0,
 67985.0,
 67990.0,
 67992.0,
 100760.0,
 133531.0,
 133534.0,
 68001.0,
 68002.0,
 100769.0,
 133541.0,
 68012.0,
 68013.0,
 68015.0,
 133566.0,
 35263.0,
 68034.0,
 68036.0,
 68037.0,
 100804.0,
 100806.0,
 68040.0,
 68044.0,
 2509.0,
 133582.0,
 35280.0,
 133584.0,
 68051.0,
 35284.0,
 100821.0,
 35286.0,
 133590.0,
 2523.0,
 68061.0,
 68062.0,
 100834.0,
 35300.0,
 2535.0,
 35307.0,
 68075.0,
 100843.0,
 68078.0,
 68080.0,
 35315.0,
 133619.0,
 133625.0,
 100860.0,
 133637.0,
 35336.0,
 68108.0,
 35342.0,
 100879.0,
 100881.0,
 68114.0,
 35348.0,
 68119.0,
 133656.0,
 35354.0,
 68123.0,
 100891.0,
 68127.0,
 133664.0,
 68129.0,
 2597.0,
 68134.0,
 2599.0,
 35368.0,
 35369.0,
 2602.0,
 100901.0,
 100907.0,
 100908.0,
 133673.0,
 100918.0,
 133688.0,
 68158.0,
 133702.0,
 68173.0,
 2638.0,
 100943.0,
 2641.0,
 68177.0,
 100947.0,
 68180.0,
 133714.0,
 133715.0,
 133717.0,
 68185.0,
 100955.0,
 133723.0,
 2655.0,
 35433.0,
 133740.0,
 100975.0,
 133743.0,
 100979.0,
 133749.0,
 100984.0,
 2681.0,
 68218.0,
 68227.0,
 68229.0,
 68230.0,
 35470.0,
 68238.0,
 101008.0,
 101020.0,
 101022.0,
 35489.0,
 35504.0,
 101041.0,
 101042.0,
 133821.0,
 133824.0,
 68292.0,
 35525.0,
 68295.0,
 101064.0,
 101070.0,
 101073.0,
 68308.0,
 2773.0,
 68309.0,
 101076.0,
 68317.0,
 133853.0,
 101089.0,
 101090.0,
 35561.0,
 68329.0,
 133867.0,
 133869.0,
 101102.0,
 101104.0,
 133874.0,
 101107.0,
 2804.0,
 68341.0,
 2807.0,
 35576.0,
 101113.0,
 133883.0,
 35580.0,
 68350.0,
 35586.0,
 2825.0,
 101129.0,
 68363.0,
 133899.0,
 2831.0,
 133906.0,
 101144.0,
 101146.0,
 68390.0,
 2855.0,
 68391.0,
 68392.0,
 101168.0,
 101173.0,
 2872.0,
 101176.0,
 133944.0,
 68413.0,
 68418.0,
 2885.0,
 68421.0,
 68423.0,
 101195.0,
 133963.0,
 35661.0,
 101201.0,
 133976.0,
 68443.0,
 133985.0,
 35684.0,
 101221.0,
 133990.0,
 35687.0,
 133993.0,
 134000.0,
 68466.0,
 35702.0,
 101240.0,
 68474.0,
 68479.0,
 68483.0,
 134020.0,
 68485.0,
 101256.0,
 35724.0,
 2958.0,
 134034.0,
 101267.0,
 35733.0,
 68510.0,
 68517.0,
 2984.0,
 68522.0,
 68524.0,
 35761.0,
 101303.0,
 3000.0,
 134074.0,
 35772.0,
 68548.0,
 134085.0,
 101321.0,
 68554.0,
 101323.0,
 134091.0,
 68562.0,
 134100.0,
 35805.0,
 101342.0,
 68575.0,
 134111.0,
 3047.0,
 134121.0,
 35823.0,
 3056.0,
 134127.0,
 68605.0,
 35843.0,
 3084.0,
 134158.0,
 3087.0,
 35857.0,
 134164.0,
 134166.0,
 68633.0,
 35867.0,
 68644.0,
 68646.0,
 134182.0,
 3117.0,
 68655.0,
 134198.0,
 3139.0,
 68678.0,
 101447.0,
 3145.0,
 101453.0,
 101458.0,
 35923.0,
 101462.0,
 ...}

In [131]:
df_train['Annual Income'] = df_train['Annual Income'].fillna('None')
df_test['Annual Income']  = df_test['Annual Income'].fillna('None')

In [132]:
df_train['Annual Income'] = df_train['Annual Income'].astype(str)
df_test['Annual Income']  = df_test['Annual Income'].astype(str)

In [133]:
all_vals = pd.concat([
    df_train['Annual Income'],
    df_test['Annual Income']
])

label.fit(all_vals)

LabelEncoder()

In [134]:
df_train['Annual Income'] = label.transform(df_train['Annual Income'])
df_test['Annual Income'] = label.transform(df_test['Annual Income'])

In [135]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [136]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1181471 non-null  object
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(7), int64(3), object(10)
memory usage: 183.1+ MB

In [137]:
set(df_test['Marital Status']).difference(set(df_train['Marital Status']))

set()

In [138]:
df_train['Marital Status'] = df_train['Marital Status'].fillna('None')
df_test['Marital Status']  = df_test['Marital Status'].fillna('None')

In [139]:
df_train['Marital Status'] = df_train['Marital Status'].astype(str)
df_test['Marital Status']  = df_test['Marital Status'].astype(str)

In [140]:
all_vals = pd.concat([
    df_train['Marital Status'],
    df_test['Marital Status']
])

label.fit(all_vals)

LabelEncoder()

In [141]:
df_train['Marital Status'] = label.transform(df_train['Marital Status'])
df_test['Marital Status'] = label.transform(df_test['Marital Status'])

In [142]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [143]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1090328 non-null  float64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(7), int64(4), object(9)
memory usage: 183.1+ MB

In [144]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents    109672
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [145]:
df_train['Number of Dependents'] = df_train['Number of Dependents'].fillna('None')
df_test['Number of Dependents'] = df_test['Number of Dependents'].fillna('None')

In [146]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [147]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [148]:
set(df_test['Number of Dependents']).difference(set(df_train['Number of Dependents']))

set()

In [149]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  object
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(4), object(10)
memory usage: 183.1+ MB

In [150]:
df_train['Number of Dependents'] = df_train['Number of Dependents'].astype(str)
df_test['Number of Dependents'] = df_test['Number of Dependents'].astype(str)

In [151]:
df_train['Number of Dependents'] = label.fit_transform(df_train['Number of Dependents'])
df_test['Number of Dependents'] = label.transform(df_test['Number of Dependents'])

In [152]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [153]:
df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation              239125
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [154]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  object
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(5), object(9)
memory usage: 183.1+ MB

In [155]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [156]:
df_train['Education Level'] = label.fit_transform(df_train['Education Level'])
df_test['Education Level'] = label.transform(df_test['Education Level'])

In [157]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [158]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  int64
 6   Occupation            841925 non-null   object
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(6), object(8)
memory usage: 183.1+ MB

In [159]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [160]:
set(df_test['Occupation']).difference(set(df_train['Occupation']))

set()

In [161]:
df_train['Occupation'] = df_train['Occupation'].fillna('None')
df_test['Occupation'] = df_test['Occupation'].fillna('None')

In [162]:
df_train['Occupation'] = label.fit_transform(df_train['Occupation'])
df_test['Occupation'] = label.transform(df_test['Occupation'])

In [163]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  int64
 6   Occupation            1200000 non-null  int64
 7   Health Score          1125924 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(7), object(7)
memory usage: 183.1+ MB

In [164]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [165]:
df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [166]:
# train
df_train['Health Score'] = pd.to_numeric(
    df_train['Health Score'], errors='coerce'
)

df_test['Health Score'] = pd.to_numeric(
    df_test['Health Score'], errors='coerce'
)
median_hs = df_train['Health Score'].median()
df_train['Health Score'] = df_train['Health Score'].fillna(median_hs)
df_test['Health Score']  = df_test['Health Score'].fillna(median_hs)

In [167]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                 object
Policy Type              object
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Policy Start Date        object
Customer Feedback        object
Smoking Status           object
Exercise Frequency       object
Property Type            object
Premium Amount          float64
dtype: object

In [168]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  int64
 6   Occupation            1200000 non-null  int64
 7   Health Score          1200000 non-null  float64
 8   Location              1200000 non-null  object
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(7), object(7)
memory usage: 183.1+ MB

In [169]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score                 0
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [170]:
df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score                 0
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [171]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [172]:
set(df_test['Location']).difference(set(df_train['Location']))

set()

In [173]:
df_train['Location'] = label.fit_transform(df_train['Location'])
df_test['Location'] = label.transform(df_test['Location'])

In [174]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  int64
 6   Occupation            1200000 non-null  int64
 7   Health Score          1200000 non-null  float64
 8   Location              1200000 non-null  int64
 9   Policy Type           1200000 non-null  object
 10  Previous Claims       835971 non-null   float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1062118 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Policy Start Date     1200000 non-null  object
 15  Customer Feedback     1122176 non-null  object
 16  Smoking Status        1200000 non-null  object
 17  Exercise Frequency    1200000 non-null  object
 18  Property Type         1200000 non-null  object
 19  Premium Amount        1200000 non-null  float64
dtypes: float64(6), int64(8), object(6)
memory usage: 183.1+ MB

In [175]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [176]:
for df in [df_train, df_test]:
    df['Policy Start Date'] = pd.to_datetime(
        df['Policy Start Date'], errors='coerce'
    )

    df['policy_year']  = df['Policy Start Date'].dt.year
    df['policy_month'] = df['Policy Start Date'].dt.month
    df['policy_day']   = df['Policy Start Date'].dt.day

    df.drop(columns=['Policy Start Date'], inplace=True)

In [177]:
X_train = df_train.drop('Premium Amount', axis=1)
y_train = df_train['Premium Amount']
X_test  = df_test.copy()

In [178]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_train['Policy Type'] = le.fit_transform(df_train['Policy Type'])
df_test['Policy Type']  = le.transform(df_test['Policy Type'])

In [179]:
X_train.select_dtypes(include='object')

,Policy Type,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
0,Premium,Poor,No,Weekly,House
1,Comprehensive,Average,Yes,Monthly,House
2,Premium,Good,Yes,Weekly,House
3,Basic,Poor,Yes,Daily,Apartment
4,Premium,Poor,Yes,Weekly,House
...,...,...,...,...,...
1199995,Premium,Poor,No,Daily,Apartment
1199996,Comprehensive,Poor,No,Weekly,Apartment
1199997,Basic,Good,No,Monthly,Condo
1199998,Premium,Poor,No,Daily,Apartment
1199999,Premium,Good,Yes,Monthly,House

In [180]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                  int64
Policy Type               int64
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Customer Feedback        object
Smoking Status           object
Exercise Frequency       object
Property Type            object
Premium Amount          float64
policy_year               int32
policy_month              int32
policy_day                int32
dtype: object

In [181]:
df_train.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score                 0
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
policy_year                  0
policy_month                 0
policy_day                   0
dtype: int64

In [182]:
df_test.isna().sum()

Age                          0
Gender                       0
Annual Income                0
Marital Status               0
Number of Dependents         0
Education Level              0
Occupation                   0
Health Score                 0
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
policy_year                  0
policy_month                 0
policy_day                   0
dtype: int64

In [183]:
# train
df_train['Previous Claims'] = pd.to_numeric(
    df_train['Previous Claims'], errors='coerce'
)

# test
df_test['Previous Claims'] = pd.to_numeric(
    df_test['Previous Claims'], errors='coerce'
)
median_hs = df_train['Previous Claims'].median()
df_train['Previous Claims'] = df_train['Previous Claims'].fillna(median_hs)
df_test['Previous Claims']  = df_test['Previous Claims'].fillna(median_hs)

In [184]:
df_train['Credit Score'] = pd.to_numeric(
    df_train['Credit Score'],errors = 'coerce'
)

df_test['Credit Score'] = pd.to_numeric(
    df_test['Credit Score'],errors = 'coerce'
)
median_hs = df_train['Credit Score'].median()
df_train['Credit Score'] = df_train['Credit Score'].fillna(median_hs)
df_test['Credit Score'] = df_test['Credit Score'].fillna(median_hs)

In [185]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                  int64
Policy Type               int64
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Customer Feedback        object
Smoking Status           object
Exercise Frequency       object
Property Type            object
Premium Amount          float64
policy_year               int32
policy_month              int32
policy_day                int32
dtype: object

In [186]:
df_train.isna().sum()

Age                         0
Gender                      0
Annual Income               0
Marital Status              0
Number of Dependents        0
Education Level             0
Occupation                  0
Health Score                0
Location                    0
Policy Type                 0
Previous Claims             0
Vehicle Age                 6
Credit Score                0
Insurance Duration          1
Customer Feedback       77824
Smoking Status              0
Exercise Frequency          0
Property Type               0
Premium Amount              0
policy_year                 0
policy_month                0
policy_day                  0
dtype: int64

In [187]:
df_test.isna().sum()

Age                         0
Gender                      0
Annual Income               0
Marital Status              0
Number of Dependents        0
Education Level             0
Occupation                  0
Health Score                0
Location                    0
Policy Type                 0
Previous Claims             0
Vehicle Age                 3
Credit Score                0
Insurance Duration          2
Customer Feedback       52276
Smoking Status              0
Exercise Frequency          0
Property Type               0
policy_year                 0
policy_month                0
policy_day                  0
dtype: int64

In [188]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 22 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  int64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  int64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  int64
 5   Education Level       1200000 non-null  int64
 6   Occupation            1200000 non-null  int64
 7   Health Score          1200000 non-null  float64
 8   Location              1200000 non-null  int64
 9   Policy Type           1200000 non-null  int64
 10  Previous Claims       1200000 non-null  float64
 11  Vehicle Age           1199994 non-null  float64
 12  Credit Score          1200000 non-null  float64
 13  Insurance Duration    1199999 non-null  float64
 14  Customer Feedback     1122176 non-null  object
 15  Smoking Status        1200000 non-null  object
 16  Exercise Frequency    1200000 non-null  object
 17  Property Type         1200000 non-null  object
 18  Premium Amount        1200000 non-null  float64
 19  policy_year           1200000 non-null  int32
 20  policy_month          1200000 non-null  int32
 21  policy_day            1200000 non-null  int32
dtypes: float64(6), int32(3), int64(9), object(4)
memory usage: 187.7+ MB

In [189]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [190]:
df_train['Customer Feedback'] = pd.to_numeric(
    df_train['Customer Feedback'],errors = 'coerce'
)

df_test['Customer Feedback'] = pd.to_numeric(
    df_test['Customer Feedback'],errors = 'coerce'
)
median_hs = df_train['Customer Feedback'].median()
df_train['Customer Feedback'] = df_train['Customer Feedback'].fillna(median_hs)
df_test['Customer Feedback'] = df_test['Customer Feedback'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [191]:
df_train['Customer Feedback'] = label.fit_transform(df_train['Customer Feedback'])
df_test['Customer Feedback'] = label.transform(df_test['Customer Feedback'])

In [192]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                  int64
Policy Type               int64
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Customer Feedback         int64
Smoking Status           object
Exercise Frequency       object
Property Type            object
Premium Amount          float64
policy_year               int32
policy_month              int32
policy_day                int32
dtype: object

In [193]:
df_train.isna().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Previous Claims         0
Vehicle Age             6
Credit Score            0
Insurance Duration      1
Customer Feedback       0
Smoking Status          0
Exercise Frequency      0
Property Type           0
Premium Amount          0
policy_year             0
policy_month            0
policy_day              0
dtype: int64

In [194]:
df_test.isna().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Previous Claims         0
Vehicle Age             3
Credit Score            0
Insurance Duration      2
Customer Feedback       0
Smoking Status          0
Exercise Frequency      0
Property Type           0
policy_year             0
policy_month            0
policy_day              0
dtype: int64

In [195]:
df_train['Vehicle Age'] = pd.to_numeric(
    df_train['Vehicle Age'],errors = 'coerce'
)

df_test['Vehicle Age'] = pd.to_numeric(
    df_test['Vehicle Age'],errors = 'coerce'
)
median_hs = df_train['Vehicle Age'].median()
df_train['Vehicle Age'] = df_train['Vehicle Age'].fillna(median_hs)
df_test['Vehicle Age'] = df_test['Vehicle Age'].fillna(median_hs)

In [196]:
df_train['Insurance Duration'] = pd.to_numeric(
    df_train['Insurance Duration'],errors = 'coerce'
)

df_test['Insurance Duration'] = pd.to_numeric(
    df_test['Insurance Duration'],errors = 'coerce'
)
median_hs = df_train['Insurance Duration'].median()
df_train['Insurance Duration'] = df_train['Insurance Duration'].fillna(median_hs)
df_test['Insurance Duration'] = df_test['Insurance Duration'].fillna(median_hs)

In [197]:
df_train.isna().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Previous Claims         0
Vehicle Age             0
Credit Score            0
Insurance Duration      0
Customer Feedback       0
Smoking Status          0
Exercise Frequency      0
Property Type           0
Premium Amount          0
policy_year             0
policy_month            0
policy_day              0
dtype: int64

In [198]:
df_test.isna().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
Education Level         0
Occupation              0
Health Score            0
Location                0
Policy Type             0
Previous Claims         0
Vehicle Age             0
Credit Score            0
Insurance Duration      0
Customer Feedback       0
Smoking Status          0
Exercise Frequency      0
Property Type           0
policy_year             0
policy_month            0
policy_day              0
dtype: int64

In [199]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [200]:
set(df_test['Smoking Status']).difference(set(df_train['Smoking Status']))

set()

In [201]:
df_train['Smoking Status'] = label.fit_transform(df_train['Smoking Status'])
df_test['Smoking Status'] = label.transform(df_test['Smoking Status'])

In [202]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                  int64
Policy Type               int64
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Customer Feedback         int64
Smoking Status            int64
Exercise Frequency       object
Property Type            object
Premium Amount          float64
policy_year               int32
policy_month              int32
policy_day                int32
dtype: object

In [203]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [204]:
set(df_test['Exercise Frequency']).difference(set(df_train['Exercise Frequency']))

set()

In [205]:
df_train['Exercise Frequency'] = label.fit_transform(df_train['Exercise Frequency'])
df_test['Exercise Frequency'] = label.transform(df_test['Exercise Frequency'])

In [206]:
from sklearn.preprocessing import LabelEncoder
lable = LabelEncoder()

In [207]:
set(df_test['Property Type']).difference(set(df_train['Property Type']))

set()

In [208]:
df_train['Property Type'] = label.fit_transform(df_train['Property Type'])
df_test['Property Type'] = label.transform(df_test['Property Type'])

In [209]:
df_train.dtypes

Age                       int64
Gender                    int64
Annual Income             int64
Marital Status            int64
Number of Dependents      int64
Education Level           int64
Occupation                int64
Health Score            float64
Location                  int64
Policy Type               int64
Previous Claims         float64
Vehicle Age             float64
Credit Score            float64
Insurance Duration      float64
Customer Feedback         int64
Smoking Status            int64
Exercise Frequency        int64
Property Type             int64
Premium Amount          float64
policy_year               int32
policy_month              int32
policy_day                int32
dtype: object

In [210]:
X_train = df_train.drop('Premium Amount', axis=1)
y_train = df_train['Premium Amount']
X_test = df_test.copy()

In [211]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [212]:
poly = PolynomialFeatures()
model = LinearRegression()

In [213]:
pipe =Pipeline([('poly',poly),('model',model)])

In [214]:
params = {
    'poly__degree':[1, 2, 3,4,5,6,7,8,9,10],
    'poly__include_bias':[False]
}

In [215]:
from sklearn.model_selection import GridSearchCV

In [216]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [126]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.3s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.5s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.5s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  24.4s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  22.5s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  24.2s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time= 8.8min
[CV] END ...........poly__degree=3, poly__include_bias=False; total time= 8.8min
[CV] END ...........poly__degree=3, poly__include_bias=False; total time= 7.8min

MemoryError: Unable to allocate 18.1 GiB for an array with shape (1200000, 2023) and data type float64

In [134]:
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

model = HistGradientBoostingRegressor(
    random_state=42
)

params = {
    'max_depth': [4, 6],
    'learning_rate': [0.05, 0.1],
    'max_iter': [100, 200]
}

final_model = GridSearchCV(
    model,
    params,
    cv=3,
    scoring='r2',
    verbose=2,
    n_jobs=-1
)

final_model.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits

GridSearchCV(cv=3, estimator=HistGradientBoostingRegressor(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1], 'max_depth': [4, 6],
                         'max_iter': [100, 200]},
             scoring='r2', verbose=2)

In [135]:
final_model.best_score_

np.float64(0.0205459223880123)

In [136]:
final_model.best_params_

{'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 200}

In [140]:
y_pred = final_model.predict(X_test)

In [141]:
df_sub = pd.read_csv('sample_submission.csv')

In [143]:
df_sub['Premium Amount'] = y_pred

In [144]:
df_sub.to_csv('sub.csv',index = False,index_label= False)

In [217]:
X_train.select_dtypes(include='object').head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [218]:
X_train = df_train.drop('Premium Amount', axis=1)
y_train = df_train['Premium Amount']
X_test  = df_test.copy()

In [130]:
X_train.select_dtypes(include='object')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1200000 rows x 0 columns]