In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [4]:
df_test.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty
0,630000,24,other,ba,6.85,65.2,yes,5.2,poor,group study,high,easy
1,630001,18,male,diploma,6.61,45.0,no,9.3,poor,coaching,low,easy
2,630002,24,female,b.tech,6.60,98.5,yes,6.2,good,group study,medium,moderate
3,630003,24,male,diploma,3.03,66.3,yes,5.7,average,mixed,medium,moderate
4,630004,20,female,b.tech,2.03,42.4,yes,9.2,average,coaching,low,moderate

In [5]:
df_train.isna().sum()

id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [6]:
df_test.isna().sum()

id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
dtype: int64

In [7]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               630000 non-null  int64
 1   gender            630000 non-null  object
 2   course            630000 non-null  object
 3   study_hours       630000 non-null  float64
 4   class_attendance  630000 non-null  float64
 5   internet_access   630000 non-null  object
 6   sleep_hours       630000 non-null  float64
 7   sleep_quality     630000 non-null  object
 8   study_method      630000 non-null  object
 9   facility_rating   630000 non-null  object
 10  exam_difficulty   630000 non-null  object
 11  exam_score        630000 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ MB

In [9]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               270000 non-null  int64
 1   gender            270000 non-null  object
 2   course            270000 non-null  object
 3   study_hours       270000 non-null  float64
 4   class_attendance  270000 non-null  float64
 5   internet_access   270000 non-null  object
 6   sleep_hours       270000 non-null  float64
 7   sleep_quality     270000 non-null  object
 8   study_method      270000 non-null  object
 9   facility_rating   270000 non-null  object
 10  exam_difficulty   270000 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 22.7+ MB

In [10]:
set(df_test['gender']).difference(set(df_train['gender']))

set()

In [11]:
df_train['gender'].value_counts()

gender
other     211097
male      210593
female    208310
Name: count, dtype: int64

In [12]:
df_test['gender'].value_counts()

gender
male      90682
other     90111
female    89207
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
label = LabelEncoder()

In [15]:
df_train['gender'] = label.fit_transform(df_train['gender'])
df_test['gender'] = label.transform(df_test['gender'])

In [16]:
df_train['course']

0            b.sc
1         diploma
2            b.sc
3            b.sc
4             bca
           ...
629995     b.tech
629996         ba
629997        bca
629998      b.com
629999     b.tech
Name: course, Length: 630000, dtype: object

In [17]:
set(df_test['course']).difference(set(df_train['course']))

set()

In [18]:
df_train['course'] = label.fit_transform(df_train['course'])
df_test['course'] = label.transform(df_test['course'])

In [19]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               270000 non-null  int64
 1   gender            270000 non-null  int64
 2   course            270000 non-null  int64
 3   study_hours       270000 non-null  float64
 4   class_attendance  270000 non-null  float64
 5   internet_access   270000 non-null  object
 6   sleep_hours       270000 non-null  float64
 7   sleep_quality     270000 non-null  object
 8   study_method      270000 non-null  object
 9   facility_rating   270000 non-null  object
 10  exam_difficulty   270000 non-null  object
dtypes: float64(3), int64(3), object(5)
memory usage: 22.7+ MB

In [20]:
set(df_test['internet_access']).difference(set(df_train['internet_access']))

set()

In [21]:
df_train['internet_access'] = label.fit_transform(df_train['internet_access'])
df_test['internet_access'] = label.transform(df_test['internet_access'])

In [22]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               270000 non-null  int64
 1   gender            270000 non-null  int64
 2   course            270000 non-null  int64
 3   study_hours       270000 non-null  float64
 4   class_attendance  270000 non-null  float64
 5   internet_access   270000 non-null  int64
 6   sleep_hours       270000 non-null  float64
 7   sleep_quality     270000 non-null  object
 8   study_method      270000 non-null  object
 9   facility_rating   270000 non-null  object
 10  exam_difficulty   270000 non-null  object
dtypes: float64(3), int64(4), object(4)
memory usage: 22.7+ MB

In [23]:
set(df_test['sleep_quality']).difference(set(df_train['sleep_quality']))

set()

In [24]:
df_train['sleep_quality'] = label.fit_transform(df_train['sleep_quality'])
df_test['sleep_quality'] = label.transform(df_test['sleep_quality'])

In [25]:
set(df_test['study_method']).difference(set(df_train['study_method']))

set()

In [26]:
df_train['study_method'] = label.fit_transform(df_train['study_method'])
df_test['study_method'] = label.transform(df_test['study_method'])

In [27]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               270000 non-null  int64
 1   gender            270000 non-null  int64
 2   course            270000 non-null  int64
 3   study_hours       270000 non-null  float64
 4   class_attendance  270000 non-null  float64
 5   internet_access   270000 non-null  int64
 6   sleep_hours       270000 non-null  float64
 7   sleep_quality     270000 non-null  int64
 8   study_method      270000 non-null  int64
 9   facility_rating   270000 non-null  object
 10  exam_difficulty   270000 non-null  object
dtypes: float64(3), int64(6), object(2)
memory usage: 22.7+ MB

In [28]:
set(df_test['facility_rating']).difference(set(df_train['facility_rating']))

set()

In [29]:
df_train['facility_rating'] = label.fit_transform(df_train['facility_rating'])
df_test['facility_rating'] = label.transform(df_test['facility_rating'])

In [30]:
set(df_test['exam_difficulty']).difference(set(df_train['exam_difficulty']))

set()

In [31]:
df_train['exam_difficulty'] = label.fit_transform(df_train['exam_difficulty'])
df_test['exam_difficulty'] = label.transform(df_test['exam_difficulty'])

In [32]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270000 entries, 0 to 269999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               270000 non-null  int64
 1   gender            270000 non-null  int64
 2   course            270000 non-null  int64
 3   study_hours       270000 non-null  float64
 4   class_attendance  270000 non-null  float64
 5   internet_access   270000 non-null  int64
 6   sleep_hours       270000 non-null  float64
 7   sleep_quality     270000 non-null  int64
 8   study_method      270000 non-null  int64
 9   facility_rating   270000 non-null  int64
 10  exam_difficulty   270000 non-null  int64
dtypes: float64(3), int64(8)
memory usage: 22.7 MB

In [33]:
X_train = df_train.drop('exam_score', axis=1)
y_train = df_train['exam_score']
X_test = df_test.copy()

In [34]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [35]:
poly = PolynomialFeatures()
model = LinearRegression()

In [36]:
pipe = Pipeline([('poly', poly), ('model', model)])

In [37]:
params = {
    'poly__degree':[1, 2, 3],
    'poly__include_bias':[False]
}

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [40]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.1s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.1s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.1s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.8s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.8s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.8s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   9.2s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   9.3s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   9.4s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('poly', PolynomialFeatures()),
                                       ('model', LinearRegression())]),
             param_grid={'poly__degree': [1, 2, 3],
                         'poly__include_bias': [False]},
             verbose=2)

In [41]:
final_model.best_score_

np.float64(0.7743340980162096)