In [156]:
import numpy as np
import cv2
import pandas as pd
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

In [157]:
df_train = pd.read_csv('train.csv')
df_test= pd.read_csv('test.csv')

In [158]:
df_train

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750
...,...,...,...,...,...,...,...,...,...
1780,ID983582017__Dry_Clover_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Clover_g,0.0000
1781,ID983582017__Dry_Dead_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Dead_g,0.0000
1782,ID983582017__Dry_Green_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Green_g,40.9400
1783,ID983582017__Dry_Total_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Total_g,40.9400
1784,ID983582017__GDM_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,GDM_g,40.9400

In [159]:
df_test

                    sample_id             image_path   target_name
0  ID1001187975__Dry_Clover_g  test/ID1001187975.jpg  Dry_Clover_g
1    ID1001187975__Dry_Dead_g  test/ID1001187975.jpg    Dry_Dead_g
2   ID1001187975__Dry_Green_g  test/ID1001187975.jpg   Dry_Green_g
3   ID1001187975__Dry_Total_g  test/ID1001187975.jpg   Dry_Total_g
4         ID1001187975__GDM_g  test/ID1001187975.jpg         GDM_g

In [160]:
os.listdir('train/')

['ID1011485656.jpg',
 'ID1012260530.jpg',
 'ID1025234388.jpg',
 'ID1028611175.jpg',
 'ID1035947949.jpg',
 'ID1036339023.jpg',
 'ID1049634115.jpg',
 'ID1051144034.jpg',
 'ID1052620238.jpg',
 'ID105271783.jpg',
 'ID1053972079.jpg',
 'ID1058383417.jpg',
 'ID1062837331.jpg',
 'ID1070112260.jpg',
 'ID1078930021.jpg',
 'ID1084819986.jpg',
 'ID1088965591.jpg',
 'ID1098771283.jpg',
 'ID1103883611.jpg',
 'ID1108283583.jpg',
 'ID1113121340.jpg',
 'ID1113329413.jpg',
 'ID1119739385.jpg',
 'ID1119761112.jpg',
 'ID1121692672.jpg',
 'ID1127246618.jpg',
 'ID112966473.jpg',
 'ID1131079710.jpg',
 'ID1136169672.jpg',
 'ID1139866256.jpg',
 'ID1139918758.jpg',
 'ID1140993511.jpg',
 'ID1148528732.jpg',
 'ID1148666289.jpg',
 'ID1149598723.jpg',
 'ID1159071020.jpg',
 'ID1163061745.jpg',
 'ID1168534540.jpg',
 'ID1176292407.jpg',
 'ID1182523622.jpg',
 'ID1183807388.jpg',
 'ID1193692654.jpg',
 'ID1199150612.jpg',
 'ID1208644039.jpg',
 'ID1211362607.jpg',
 'ID121331988.jpg',
 'ID1215977190.jpg',
 'ID1217108125.jpg',
 'ID1237349078.jpg',
 'ID12390962.jpg',
 'ID1244346858.jpg',
 'ID1249094008.jpg',
 'ID1251029854.jpg',
 'ID1254829053.jpg',
 'ID1268934251.jpg',
 'ID1275072698.jpg',
 'ID1277756619.jpg',
 'ID1291116815.jpg',
 'ID1294770420.jpg',
 'ID1314135397.jpg',
 'ID13162390.jpg',
 'ID1337107565.jpg',
 'ID1343327476.jpg',
 'ID1345375788.jpg',
 'ID135365668.jpg',
 'ID1354190372.jpg',
 'ID1357758282.jpg',
 'ID1357768767.jpg',
 'ID1370004842.jpg',
 'ID1374789439.jpg',
 'ID1385921939.jpg',
 'ID1386202352.jpg',
 'ID1395011773.jpg',
 'ID1403078396.jpg',
 'ID1403107574.jpg',
 'ID1411613934.jpg',
 'ID141370843.jpg',
 'ID1413758094.jpg',
 'ID1414371018.jpg',
 'ID1415329644.jpg',
 'ID1421714468.jpg',
 'ID142751858.jpg',
 'ID1428837636.jpg',
 'ID1437386574.jpg',
 'ID1444674500.jpg',
 'ID1450399782.jpg',
 'ID1451025862.jpg',
 'ID1456861072.jpg',
 'ID1457700382.jpg',
 'ID1458758610.jpg',
 'ID1463690813.jpg',
 'ID146920896.jpg',
 'ID1471216911.jpg',
 'ID1472525822.jpg',
 'ID1473228876.jpg',
 'ID1474775613.jpg',
 'ID147528735.jpg',
 'ID1476045099.jpg',
 'ID1477176296.jpg',
 'ID1488408526.jpg',
 'ID1496750796.jpg',
 'ID1498398599.jpg',
 'ID1509266870.jpg',
 'ID1510574031.jpg',
 'ID1512751450.jpg',
 'ID1513184765.jpg',
 'ID1515990019.jpg',
 'ID1516374298.jpg',
 'ID152157478.jpg',
 'ID1525817840.jpg',
 'ID1540480250.jpg',
 'ID1545077474.jpg',
 'ID1547945326.jpg',
 'ID1559189397.jpg',
 'ID1563418511.jpg',
 'ID1570190541.jpg',
 'ID1573329652.jpg',
 'ID1574125908.jpg',
 'ID157479394.jpg',
 'ID1579942839.jpg',
 'ID158170916.jpg',
 'ID1590632667.jpg',
 'ID1618145129.jpg',
 'ID1618597318.jpg',
 'ID1620371305.jpg',
 'ID162394992.jpg',
 'ID1623964968.jpg',
 'ID1624268863.jpg',
 'ID1634731537.jpg',
 'ID1638922597.jpg',
 'ID1645161155.jpg',
 'ID1655778545.jpg',
 'ID1665142816.jpg',
 'ID1667778338.jpg',
 'ID1671844336.jpg',
 'ID1675365449.jpg',
 'ID1680597197.jpg',
 'ID1692894460.jpg',
 'ID1693880739.jpg',
 'ID1703304524.jpg',
 'ID1717006117.jpg',
 'ID1729002155.jpg',
 'ID1746343319.jpg',
 'ID1753847361.jpg',
 'ID1761544403.jpg',
 'ID1781353117.jpg',
 'ID1782509721.jpg',
 'ID1782608354.jpg',
 'ID1783499590.jpg',
 'ID1784585001.jpg',
 'ID1789265307.jpg',
 'ID1789834546.jpg',
 'ID1789853061.jpg',
 'ID1831254380.jpg',
 'ID1839139621.jpg',
 'ID1853508321.jpg',
 'ID1857489997.jpg',
 'ID1859251563.jpg',
 'ID1859792585.jpg',
 'ID1868719645.jpg',
 'ID187238869.jpg',
 'ID1874904894.jpg',
 'ID1876271942.jpg',
 'ID1880764911.jpg',
 'ID1888700589.jpg',
 'ID1889150649.jpg',
 'ID1894998379.jpg',
 'ID1899025384.jpg',
 'ID1920959057.jpg',
 'ID193102215.jpg',
 'ID1946311744.jpg',
 'ID194823383.jpg',
 'ID1948354837.jpg',
 'ID1952813879.jpg',
 'ID1953171547.jpg',
 'ID1953218650.jpg',
 'ID1954669045.jpg',
 'ID1962197151.jpg',
 'ID1962379474.jpg',
 'ID1963715583.jpg',
 'ID196516535.jpg',
 'ID1970522802.jpg',
 'ID1976436386.jpg',
 'ID1980675327.jpg',
 'ID1982662138.jpg',
 'ID1988033238.jpg',
 'ID1989506559.jpg',
 'ID1993907137.jpg',
 'ID1997244125.jpg',
 'ID2002797732.jpg',
 'ID2003438517.jpg',
 'ID2006686196.jpg',
 'ID2010625680.jpg',
 'ID2014192906.jpg',
 'ID2030696575.jpg',
 'ID2037861084.jpg',
 'ID2048645043.jpg',
 'ID2052442675.jpg',
 'ID2052993274.jpg',
 'ID2053315094.jpg',
 'ID2056023629.jpg',
 'ID2056982009.jpg',
 'ID2069766023.jpg',
 'ID2086966681.jpg',
 'ID2089023774.jpg',
 'ID2091439402.jpg',
 'ID2096636211.jpg',
 'ID2099464826.jpg',
 'ID2099742797.jpg',
 'ID210865340.jpg',
 'ID212206250.jpg',
 'ID212206832.jpg',
 'ID2125100696.jpg',
 'ID2131261930.jpg',
 'ID21377800.jpg',
 'ID2145635095.jpg',
 'ID227847873.jpg',
 'ID230058600.jpg',
 'ID249042826.jpg',
 'ID257822026.jpg',
 'ID290369222.jpg',
 'ID294150104.jpg',
 'ID307060225.jpg',
 'ID315357834.jpg',
 'ID317990700.jpg',
 'ID325799913.jpg',
 'ID332742639.jpg',
 'ID342818398.jpg',
 'ID344618040.jpg',
 'ID353424190.jpg',
 'ID353997899.jpg',
 'ID354528442.jpg',
 'ID363069566.jpg',
 'ID364856705.jpg',
 'ID380752847.jpg',
 'ID383231615.jpg',
 'ID384648061.jpg',
 'ID386216505.jpg',
 'ID397994621.jpg',
 'ID407646960.jpg',
 'ID40849327.jpg',
 'ID415656958.jpg',
 'ID423506847.jpg',
 'ID429799190.jpg',
 'ID431471530.jpg',
 'ID443091455.jpg',
 'ID4464212.jpg',
 'ID471758347.jpg',
 'ID473494649.jpg',
 'ID475010202.jpg',
 'ID482555369.jpg',
 'ID48303557.jpg',
 'ID488873801.jpg',
 'ID490139972.jpg',
 'ID498304885.jpg',
 'ID50027657.jpg',
 'ID520514019.jpg',
 'ID528010569.jpg',
 'ID529933668.jpg',
 'ID534966093.jpg',
 'ID54128926.jpg',
 'ID544444725.jpg',
 'ID545360459.jpg',
 'ID550623196.jpg',
 'ID552040066.jpg',
 'ID554314721.jpg',
 'ID560946727.jpg',
 'ID566966892.jpg',
 'ID567744300.jpg',
 'ID572336285.jpg',
 'ID574213894.jpg',
 'ID576137678.jpg',
 'ID576621307.jpg',
 'ID577112774.jpg',
 'ID587125778.jpg',
 'ID588120964.jpg',
 'ID600602588.jpg',
 'ID605134229.jpg',
 'ID610397481.jpg',
 'ID617132135.jpg',
 'ID61833032.jpg',
 'ID6269659.jpg',
 'ID629980789.jpg',
 'ID633775166.jpg',
 'ID638711343.jpg',
 'ID656251220.jpg',
 'ID657448172.jpg',
 'ID661372352.jpg',
 'ID661817669.jpg',
 'ID663006174.jpg',
 'ID667059550.jpg',
 'ID668330410.jpg',
 'ID668475812.jpg',
 'ID670276799.jpg',
 'ID679913293.jpg',
 'ID681680726.jpg',
 'ID684062938.jpg',
 'ID684383343.jpg',
 'ID686797154.jpg',
 'ID697059386.jpg',
 'ID697718693.jpg',
 'ID698608346.jpg',
 'ID706288721.jpg',
 'ID710341728.jpg',
 'ID71885430.jpg',
 'ID72895391.jpg',
 'ID740402124.jpg',
 'ID742198710.jpg',
 'ID743847993.jpg',
 'ID746335827.jpg',
 'ID748979397.jpg',
 'ID750820644.jpg',
 'ID751517087.jpg',
 'ID753699705.jpg',
 'ID755710743.jpg',
 'ID761508093.jpg',
 'ID779628955.jpg',
 'ID7850481.jpg',
 'ID786365141.jpg',
 'ID789169173.jpg',
 'ID793526563.jpg',
 'ID797502182.jpg',
 'ID799079114.jpg',
 'ID802547515.jpg',
 'ID803479541.jpg',
 'ID808079729.jpg',
 'ID808093827.jpg',
 'ID8209776.jpg',
 'ID828217731.jpg',
 'ID839432753.jpg',
 'ID846154859.jpg',
 'ID846984946.jpg',
 'ID853954911.jpg',
 'ID866684633.jpg',
 'ID871463897.jpg',
 'ID875119737.jpg',
 'ID885388135.jpg',
 'ID896386823.jpg',
 'ID900012207.jpg',
 'ID905397692.jpg',
 'ID908524512.jpg',
 'ID914754166.jpg',
 'ID930534670.jpg',
 'ID936984905.jpg',
 'ID94564238.jpg',
 'ID950496197.jpg',
 'ID95050718.jpg',
 'ID956512130.jpg',
 'ID963903358.jpg',
 'ID968643034.jpg',
 'ID969218269.jpg',
 'ID972274220.jpg',
 'ID975115267.jpg',
 'ID978026131.jpg',
 'ID980538882.jpg',
 'ID980878870.jpg',
 'ID983582017.jpg']

In [161]:
df_train = df_train[["image_path", "target_name", "target"]]

In [162]:
df_train.head()

               image_path   target_name   target
0  train/ID1011485656.jpg  Dry_Clover_g   0.0000
1  train/ID1011485656.jpg    Dry_Dead_g  31.9984
2  train/ID1011485656.jpg   Dry_Green_g  16.2751
3  train/ID1011485656.jpg   Dry_Total_g  48.2735
4  train/ID1011485656.jpg         GDM_g  16.2750

In [163]:
X_csv = df_train[["image_path", "target_name"]]

In [164]:
y_csv = df_train['target']

In [165]:
X_csv

                  image_path   target_name
0     train/ID1011485656.jpg  Dry_Clover_g
1     train/ID1011485656.jpg    Dry_Dead_g
2     train/ID1011485656.jpg   Dry_Green_g
3     train/ID1011485656.jpg   Dry_Total_g
4     train/ID1011485656.jpg         GDM_g
...                      ...           ...
1780   train/ID983582017.jpg  Dry_Clover_g
1781   train/ID983582017.jpg    Dry_Dead_g
1782   train/ID983582017.jpg   Dry_Green_g
1783   train/ID983582017.jpg   Dry_Total_g
1784   train/ID983582017.jpg         GDM_g

[1785 rows x 2 columns]

In [166]:
y_csv

0        0.0000
1       31.9984
2       16.2751
3       48.2735
4       16.2750
         ...
1780     0.0000
1781     0.0000
1782    40.9400
1783    40.9400
1784    40.9400
Name: target, Length: 1785, dtype: float64

In [167]:
from sklearn.preprocessing import LabelEncoder

In [168]:
label = LabelEncoder()

In [169]:
X_csv['target_name'] = label.fit_transform(X_csv['target_name'])

C:\Users\USER\AppData\Local\Temp\ipykernel_12904\2820114327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_csv['target_name'] = label.fit_transform(X_csv['target_name'])

In [170]:
X_csv

                  image_path  target_name
0     train/ID1011485656.jpg            0
1     train/ID1011485656.jpg            1
2     train/ID1011485656.jpg            2
3     train/ID1011485656.jpg            3
4     train/ID1011485656.jpg            4
...                      ...          ...
1780   train/ID983582017.jpg            0
1781   train/ID983582017.jpg            1
1782   train/ID983582017.jpg            2
1783   train/ID983582017.jpg            3
1784   train/ID983582017.jpg            4

[1785 rows x 2 columns]

In [171]:
label = {
'Dry_Clover_g': 0,
'Dry_Dead_g': 1,
'Dry_Green_g': 2,
'Dry_Total_g': 3,
'GDM_g': 4
}

In [172]:
df = pd.read_csv("train.csv")

X = []
y = []

for i in range(len(df)):
    
    img_path = df["image_path"][i]
    label = df["target"][i]

    image = cv2.imread(img_path)
    image = cv2.resize(image,(224,224))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    image = preprocess_input(image)
    X.append(image)
    y.append(label)

X = np.array(X)
y = np.array(y)

In [173]:
X.shape

(1785, 224, 224, 3)

In [174]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [175]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=10,
    zoom_range=0.1,
    horizontal_flip=True
)

In [176]:
train_generator = datagen.flow(
    X_train,
    y_train,
    batch_size=32
)

In [177]:
base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)
for layer in base_model.layers:
    layer.trainable = False

In [185]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model

In [186]:
x = base_model.output
x = GlobalAveragePooling2D()(x)

x = Dense(256, activation="relu")(x)
x = Dropout(0.3)(x)

predictions = Dense(1)(x)

model = Model(inputs=base_model.input, outputs=predictions)

In [187]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-6),
    loss='mse',
    metrics=['mae']
)

In [188]:
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

In [189]:
history = model.fit(
    train_generator,
    validation_data=(X_val, y_val),
    epochs=10,
    callbacks=[early_stop]
)

Epoch 1/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 25s 406ms/step - loss: 1270.1179 - mae: 24.5946 - val_loss: 1329.3549 - val_mae: 25.6118
Epoch 2/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 380ms/step - loss: 1252.0231 - mae: 24.3242 - val_loss: 1320.3003 - val_mae: 25.4789
Epoch 3/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 378ms/step - loss: 1233.4216 - mae: 24.0341 - val_loss: 1310.0011 - val_mae: 25.3326
Epoch 4/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 385ms/step - loss: 1213.7134 - mae: 23.7628 - val_loss: 1298.9523 - val_mae: 25.1768
Epoch 5/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 384ms/step - loss: 1192.0981 - mae: 23.4675 - val_loss: 1286.7013 - val_mae: 25.0035
Epoch 6/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 398ms/step - loss: 1170.0891 - mae: 23.1578 - val_loss: 1273.7629 - val_mae: 24.8202
Epoch 7/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 400ms/step - loss: 1147.9832 - mae: 22.8286 - val_loss: 1259.6520 - val_mae: 24.6163
Epoch 8/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 408ms/step - loss: 1121.0752 - mae: 22.4705 - val_loss: 1243.6230 - val_mae: 24.3841
Epoch 9/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 400ms/step - loss: 1090.3252 - mae: 22.0916 - val_loss: 1227.3265 - val_mae: 24.1486
Epoch 10/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 400ms/step - loss: 1062.7433 - mae: 21.7406 - val_loss: 1209.4117 - val_mae: 23.8932

In [190]:
for layer in base_model.layers[-15:]:
    layer.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="mse",
    metrics=["mae"]
)

history = model.fit(
    train_generator,
    validation_data=(X_val, y_val),
    epochs=10,
    callbacks=[early_stop]
)

Epoch 1/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 25s 408ms/step - loss: 1027.4534 - mae: 21.3254 - val_loss: 1180.9449 - val_mae: 23.5029
Epoch 2/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 381ms/step - loss: 977.1570 - mae: 20.7428 - val_loss: 1150.9163 - val_mae: 23.0955
Epoch 3/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 17s 385ms/step - loss: 932.4532 - mae: 20.2652 - val_loss: 1118.4503 - val_mae: 22.6844
Epoch 4/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 403ms/step - loss: 879.0186 - mae: 19.7423 - val_loss: 1085.6368 - val_mae: 22.2983
Epoch 5/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 401ms/step - loss: 853.5809 - mae: 19.3970 - val_loss: 1052.2806 - val_mae: 21.9149
Epoch 6/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 402ms/step - loss: 804.3895 - mae: 19.0193 - val_loss: 1019.4728 - val_mae: 21.5656
Epoch 7/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 404ms/step - loss: 761.4905 - mae: 18.7080 - val_loss: 989.9865 - val_mae: 21.2681
Epoch 8/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 405ms/step - loss: 742.9274 - mae: 18.4847 - val_loss: 961.0312 - val_mae: 20.9821
Epoch 9/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 403ms/step - loss: 719.1081 - mae: 18.3497 - val_loss: 933.0970 - val_mae: 20.7127
Epoch 10/10
45/45 ━━━━━━━━━━━━━━━━━━━━ 18s 408ms/step - loss: 688.3579 - mae: 18.0753 - val_loss: 908.5905 - val_mae: 20.4893