In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train.head()

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312

In [4]:
df_test.head()

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg)
0,300000,Puma,Leather,Small,2.0,No,No,Tote,Green,20.671147
1,300001,Nike,Canvas,Medium,7.0,No,Yes,Backpack,Green,13.564105
2,300002,Adidas,Canvas,Large,9.0,No,Yes,Messenger,Blue,11.809799
3,300003,Adidas,Nylon,Large,1.0,Yes,No,Messenger,Green,18.477036
4,300004,NaN,Nylon,Large,2.0,Yes,Yes,Tote,Black,9.907953

In [5]:
df_train.isna().sum()

id                         0
Brand                   9705
Material                8347
Size                    6595
Compartments               0
Laptop Compartment      7444
Waterproof              7050
Style                   7970
Color                   9950
Weight Capacity (kg)     138
Price                      0
dtype: int64

In [6]:
df_test.isna().sum()

id                         0
Brand                   6227
Material                5613
Size                    4381
Compartments               0
Laptop Compartment      4962
Waterproof              4811
Style                   5153
Color                   6785
Weight Capacity (kg)      77
dtype: int64

In [7]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 290295 non-null  object
 1   Material              291653 non-null  object
 2   Size                  293405 non-null  object
 3   Compartments          300000 non-null  float64
 4   Laptop Compartment    292556 non-null  object
 5   Waterproof            292950 non-null  object
 6   Style                 292030 non-null  object
 7   Color                 290050 non-null  object
 8   Weight Capacity (kg)  299862 non-null  float64
 9   Price                 300000 non-null  float64
dtypes: float64(3), object(7)
memory usage: 22.9+ MB

In [9]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [10]:
set(df_train['Brand']).difference(set(df_test['Brand']))

set()

In [11]:
df_train['Brand'] = pd.to_numeric(
    df_train['Brand'],errors = 'coerce'
)

df_test['Brand'] = pd.to_numeric(
    df_test['Brand'],errors = 'coerce'
)
median_hs = df_train['Brand'].median()
df_train['Brand'] = df_train['Brand'].fillna(median_hs)
df_test['Brand'] = df_test['Brand'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [12]:
df_train['Brand'] = label.fit_transform(df_train['Brand'])
df_test['Brand'] = label.transform(df_test['Brand'])

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 300000 non-null  int64
 1   Material              291653 non-null  object
 2   Size                  293405 non-null  object
 3   Compartments          300000 non-null  float64
 4   Laptop Compartment    292556 non-null  object
 5   Waterproof            292950 non-null  object
 6   Style                 292030 non-null  object
 7   Color                 290050 non-null  object
 8   Weight Capacity (kg)  299862 non-null  float64
 9   Price                 300000 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 22.9+ MB

In [14]:
df_train.isna().sum()

Brand                      0
Material                8347
Size                    6595
Compartments               0
Laptop Compartment      7444
Waterproof              7050
Style                   7970
Color                   9950
Weight Capacity (kg)     138
Price                      0
dtype: int64

In [15]:
set(df_train['Material']).difference(set(df_test['Material']))

set()

In [16]:
df_train['Material'] = pd.to_numeric(
    df_train['Material'],errors = 'coerce'
)

df_test['Material'] = pd.to_numeric(
    df_test['Material'],errors = 'coerce'
)
median_hs = df_train['Material'].median()
df_train['Material'] = df_train['Material'].fillna(median_hs)
df_test['Material'] = df_test['Material'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [17]:
df_train['Material'] = label.fit_transform(df_train['Material'])
df_test['Material'] = label.transform(df_test['Material'])

In [18]:
set(df_test['Size']).difference(set(df_train['Size']))

set()

In [19]:
df_train['Size'] = pd.to_numeric(
    df_train['Size'],errors = 'coerce'
)

df_test['Size'] = pd.to_numeric(
    df_test['Size'],errors = 'coerce'
)
median_hs = df_train['Size'].median()
df_train['Size'] = df_train['Size'].fillna(median_hs)
df_test['Size'] = df_test['Size'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [20]:
df_train['Size'] = label.fit_transform(df_train['Size'])
df_test['Size'] = label.transform(df_test['Size'])

In [21]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 300000 non-null  int64
 1   Material              300000 non-null  int64
 2   Size                  300000 non-null  int64
 3   Compartments          300000 non-null  float64
 4   Laptop Compartment    292556 non-null  object
 5   Waterproof            292950 non-null  object
 6   Style                 292030 non-null  object
 7   Color                 290050 non-null  object
 8   Weight Capacity (kg)  299862 non-null  float64
 9   Price                 300000 non-null  float64
dtypes: float64(3), int64(3), object(4)
memory usage: 22.9+ MB

In [22]:
df_train.isna().sum()

Brand                      0
Material                   0
Size                       0
Compartments               0
Laptop Compartment      7444
Waterproof              7050
Style                   7970
Color                   9950
Weight Capacity (kg)     138
Price                      0
dtype: int64

In [23]:
df_test.isna().sum()

Brand                      0
Material                   0
Size                       0
Compartments               0
Laptop Compartment      4962
Waterproof              4811
Style                   5153
Color                   6785
Weight Capacity (kg)      77
dtype: int64

In [24]:
set(df_train['Laptop Compartment']).difference(set(df_test['Laptop Compartment']))

set()

In [25]:
df_train['Laptop Compartment'] = pd.to_numeric(
    df_train['Laptop Compartment'],errors = 'coerce'
)

df_test['Laptop Compartment'] = pd.to_numeric(
    df_test['Laptop Compartment'],errors = 'coerce'
)
median_hs = df_train['Laptop Compartment'].median()
df_train['Laptop Compartment'] = df_train['Laptop Compartment'].fillna(median_hs)
df_test['Laptop Compartment'] = df_test['Laptop Compartment'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [26]:
df_train['Laptop Compartment'] = label.fit_transform(df_train['Laptop Compartment'])
df_test['Laptop Compartment'] = label.transform(df_test['Laptop Compartment'])

In [27]:
set(df_test['Waterproof']).difference(set(df_train['Waterproof']))

set()

In [28]:
df_train['Waterproof'] = pd.to_numeric(
    df_train['Waterproof'],errors = 'coerce')

df_test['Waterproof'] = pd.to_numeric(
    df_test['Waterproof'],errors = 'coerce')
median_hs = df_train['Waterproof'].median()
df_train['Waterproof'] = df_train['Waterproof'].fillna(median_hs)
df_test['Waterproof'] = df_test['Waterproof'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [29]:
df_train['Waterproof'] = label.fit_transform(df_train['Waterproof'])
df_test['Waterproof'] = label.transform(df_test['Waterproof'])

In [30]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 300000 non-null  int64
 1   Material              300000 non-null  int64
 2   Size                  300000 non-null  int64
 3   Compartments          300000 non-null  float64
 4   Laptop Compartment    300000 non-null  int64
 5   Waterproof            300000 non-null  int64
 6   Style                 292030 non-null  object
 7   Color                 290050 non-null  object
 8   Weight Capacity (kg)  299862 non-null  float64
 9   Price                 300000 non-null  float64
dtypes: float64(3), int64(5), object(2)
memory usage: 22.9+ MB

In [31]:
df_train.isna().sum()

Brand                      0
Material                   0
Size                       0
Compartments               0
Laptop Compartment         0
Waterproof                 0
Style                   7970
Color                   9950
Weight Capacity (kg)     138
Price                      0
dtype: int64

In [32]:
df_test.isna().sum()

Brand                      0
Material                   0
Size                       0
Compartments               0
Laptop Compartment         0
Waterproof                 0
Style                   5153
Color                   6785
Weight Capacity (kg)      77
dtype: int64

In [33]:
set(df_test['Style']).difference(set(df_train['Style']))

set()

In [34]:
df_train['Style'] = pd.to_numeric(
    df_train['Style'],errors = 'coerce')

df_test['Style'] = pd.to_numeric(
    df_test['Style'],errors = 'coerce')
median_hs = df_train['Style'].median()
df_train['Style'] = df_train['Style'].fillna(median_hs)
df_test['Style'] = df_test['Style'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [35]:
df_train['Style'] = label.fit_transform(df_train['Style'])
df_test['Style'] = label.transform(df_test['Style'])

In [36]:
set(df_test['Color']).difference(set(df_train['Color']))

set()

In [37]:
df_train['Color'] = pd.to_numeric(
    df_train['Color'],errors = 'coerce')

df_test['Color'] = pd.to_numeric(
    df_test['Color'],errors = 'coerce')
median_hs = df_train['Color'].median()
df_train['Color'] = df_train['Color'].fillna(median_hs)
df_test['Color'] = df_test['Color'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [41]:
df_train['Color'] = label.fit_transform(df_train['Color'])
df_test['Color'] = label.transform(df_test['Color'])

In [42]:
df_train['Weight Capacity (kg)'] = pd.to_numeric(
    df_train['Weight Capacity (kg)'],errors = 'coerce')

df_test['Weight Capacity (kg)'] = pd.to_numeric(
    df_test['Weight Capacity (kg)'],errors = 'coerce')
median_hs = df_train['Weight Capacity (kg)'].median()
df_train['Weight Capacity (kg)'] = df_train['Weight Capacity (kg)'].fillna(median_hs)
df_test['Weight Capacity (kg)'] = df_test['Weight Capacity (kg)'].fillna(median_hs)

In [43]:
df_train['Weight Capacity (kg)'] = label.fit_transform(df_train['Weight Capacity (kg)'])
df_test['Weight Capacity (kg)'] = label.transform(df_test['Weight Capacity (kg)'])

In [44]:
X_train = df_train.drop('Price', axis=1)
y_train = df_train['Price']
X_test = df_test.copy()

In [45]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [46]:
poly = PolynomialFeatures()
model = LinearRegression()

In [47]:
pipe =Pipeline([('poly',poly),('model',model)])

In [48]:
params = {
    'poly__degree':[1, 2, 3,4,5,6],
    'poly__include_bias':[False]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [ ]:
final_model.fit(X_train, y_train)

In [ ]:
final_model.best_score_

In [ ]:
final_model.best_params_

In [ ]:
y_pred = final_model.predict(X_test)

In [ ]:
df_sub = pd.read_csv('sample_submission.csv')

In [ ]:
df_sub['Price'] = y_pred

In [123]:
df_sub.to_csv('sub.csv',index = False,index_label= False)

In [124]:
df_sub

            id      Price
0       300000  79.092385
1       300001  78.898688
2       300002  78.761599
3       300003  79.105371
4       300004  79.091778
...        ...        ...
199995  499995  79.091668
199996  499996  78.761309
199997  499997  78.762470
199998  499998  78.681148
199999  499999  78.835384

[200000 rows x 2 columns]

In [49]:
training_extra = pd.read_csv("training_extra.csv")

In [50]:
df_train = pd.concat([training_extra, df_train])

In [52]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3994318 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   id                    float64
 1   Brand                 object
 2   Material              object
 3   Size                  object
 4   Compartments          float64
 5   Laptop Compartment    object
 6   Waterproof            object
 7   Style                 object
 8   Color                 object
 9   Weight Capacity (kg)  float64
 10  Price                 float64
dtypes: float64(4), object(7)
memory usage: 365.7+ MB

In [53]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [54]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Brand                 200000 non-null  int64
 1   Material              200000 non-null  int64
 2   Size                  200000 non-null  int64
 3   Compartments          200000 non-null  float64
 4   Laptop Compartment    200000 non-null  int64
 5   Waterproof            200000 non-null  int64
 6   Style                 200000 non-null  int64
 7   Color                 200000 non-null  int64
 8   Weight Capacity (kg)  200000 non-null  int64
dtypes: float64(1), int64(8)
memory usage: 13.7 MB

In [55]:
df_train.isna().sum()

id                      300000
Brand                   117053
Material                102615
Size                     81190
Compartments                 0
Laptop Compartment       91089
Waterproof               87274
Style                    96210
Color                   123667
Weight Capacity (kg)      1670
Price                        0
dtype: int64

In [56]:
df_train = df_train.drop('id', axis=1)

In [57]:
df_test.isna().sum()

Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
dtype: int64

In [58]:
df_train['Brand'] = pd.to_numeric(
    df_train['Brand'],errors = 'coerce')

df_test['Brand'] = pd.to_numeric(
    df_test['Brand'],errors = 'coerce')
median_hs = df_train['Brand'].median()
df_train['Brand'] = df_train['Brand'].fillna(median_hs)
df_test['Brand'] = df_test['Brand'].fillna(median_hs)

In [59]:
df_train['Brand'] = label.fit_transform(df_train['Brand'])
df_test['Brand'] = label.transform(df_test['Brand'])

In [60]:
df_train['Material'] = pd.to_numeric(
    df_train['Material'],errors = 'coerce')

df_test['Material'] = pd.to_numeric(
    df_test['Material'],errors = 'coerce')
median_hs = df_train['Material'].median()
df_train['Material'] = df_train['Material'].fillna(median_hs)
df_test['Material'] = df_test['Material'].fillna(median_hs)

In [61]:
df_train['Material'] = label.fit_transform(df_train['Material'])
df_test['Material'] = label.transform(df_test['Material'])

In [62]:
df_train['Size'] = pd.to_numeric(
    df_train['Size'],errors = 'coerce')

df_test['Size'] = pd.to_numeric(
    df_test['Size'],errors = 'coerce')
median_hs = df_train['Size'].median()
df_train['Size'] = df_train['Size'].fillna(median_hs)
df_test['Size'] = df_test['Size'].fillna(median_hs)

In [63]:
df_train['Size'] = label.fit_transform(df_train['Size'])
df_test['Size'] = label.transform(df_test['Size'])

In [64]:
df_train['Laptop Compartment'] = pd.to_numeric(
    df_train['Laptop Compartment'],errors = 'coerce')

df_test['Laptop Compartment'] = pd.to_numeric(
    df_test['Laptop Compartment'],errors = 'coerce')
median_hs = df_train['Laptop Compartment'].median()
df_train['Laptop Compartment'] = df_train['Laptop Compartment'].fillna(median_hs)
df_test['Laptop Compartment'] = df_test['Laptop Compartment'].fillna(median_hs)

In [65]:
df_train['Laptop Compartment'] = label.fit_transform(df_train['Laptop Compartment'])
df_test['Laptop Compartment'] = label.transform(df_test['Laptop Compartment'])

In [66]:
df_train['Waterproof'] = pd.to_numeric(
    df_train['Waterproof'],errors = 'coerce')

df_test['Waterproof'] = pd.to_numeric(
    df_test['Waterproof'],errors = 'coerce')
median_hs = df_train['Waterproof'].median()
df_train['Waterproof'] = df_train['Waterproof'].fillna(median_hs)
df_test['Waterproof'] = df_test['Waterproof'].fillna(median_hs)

In [67]:
df_train['Waterproof'] = label.fit_transform(df_train['Waterproof'])
df_test['Waterproof'] = label.transform(df_test['Waterproof'])

In [68]:
df_train['Style'] = pd.to_numeric(
    df_train['Style'],errors = 'coerce')

df_test['Style'] = pd.to_numeric(
    df_test['Style'],errors = 'coerce')
median_hs = df_train['Style'].median()
df_train['Style'] = df_train['Style'].fillna(median_hs)
df_test['Style'] = df_test['Style'].fillna(median_hs)

In [69]:
df_train['Style'] = label.fit_transform(df_train['Style'])
df_test['Style'] = label.transform(df_test['Style'])

In [70]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3994318 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column                Dtype
---  ------                -----
 0   Brand                 int64
 1   Material              int64
 2   Size                  int64
 3   Compartments          float64
 4   Laptop Compartment    int64
 5   Waterproof            int64
 6   Style                 int64
 7   Color                 object
 8   Weight Capacity (kg)  float64
 9   Price                 float64
dtypes: float64(3), int64(6), object(1)
memory usage: 335.2+ MB

In [71]:
df_train['Color'] = pd.to_numeric(
    df_train['Color'],errors = 'coerce')

df_test['Color'] = pd.to_numeric(
    df_test['Color'],errors = 'coerce')
median_hs = df_train['Color'].median()
df_train['Color'] = df_train['Color'].fillna(median_hs)
df_test['Color'] = df_test['Color'].fillna(median_hs)

In [72]:
df_train['Color'] = label.fit_transform(df_train['Color'])
df_test['Color'] = label.transform(df_test['Color'])

In [73]:
df_train['Weight Capacity (kg)'] = pd.to_numeric(
    df_train['Weight Capacity (kg)'],errors = 'coerce')

df_test['Weight Capacity (kg)'] = pd.to_numeric(
    df_test['Weight Capacity (kg)'],errors = 'coerce')
median_hs = df_train['Weight Capacity (kg)'].median()
df_train['Weight Capacity (kg)'] = df_train['Weight Capacity (kg)'].fillna(median_hs)
df_test['Weight Capacity (kg)'] = df_test['Weight Capacity (kg)'].fillna(median_hs)

In [74]:
df_train['Weight Capacity (kg)'] = label.fit_transform(df_train['Weight Capacity (kg)'])
df_test['Weight Capacity (kg)'] = label.transform(df_test['Weight Capacity (kg)'])

In [75]:
X_train = df_train.drop('Price', axis=1)
y_train = df_train['Price']
X_test = df_test.copy()

In [76]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [77]:
poly = PolynomialFeatures()
model = LinearRegression()

In [78]:
pipe =Pipeline([('poly',poly),('model',model)])

In [79]:
params = {
    'poly__degree':[1, 2, 3,4],
    'poly__include_bias':[False]
}

In [80]:
from sklearn.model_selection import GridSearchCV

In [81]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [82]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.7s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.8s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   1.9s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  10.4s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  10.3s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=  10.2s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=  42.5s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=  20.5s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=  18.7s
[CV] END ...........poly__degree=4, poly__include_bias=False; total time= 2.6min
[CV] END ...........poly__degree=4, poly__include_bias=False; total time= 2.8min
[CV] END ...........poly__degree=4, poly__include_bias=False; total time= 3.0min

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('poly', PolynomialFeatures()),
                                       ('model', LinearRegression())]),
             param_grid={'poly__degree': [1, 2, 3, 4],
                         'poly__include_bias': [False]},
             verbose=2)

In [83]:
final_model.best_score_

np.float64(0.00044501841561635686)

In [84]:
final_model.best_params_

{'poly__degree': 2, 'poly__include_bias': False}

In [85]:
y_pred = final_model.predict(X_test)

In [86]:
df_sub = pd.read_csv('sample_submission.csv')

In [87]:
df_sub['Price'] = y_pred

In [88]:
df_sub.to_csv('sub.csv',index = False,index_label= False)

In [89]:
df_sub

            id      Price
0       300000  82.092056
1       300001  81.130284
2       300002  80.626423
3       300003  81.941255
4       300004  80.117613
...        ...        ...
199995  499995  79.526867
199996  499996  79.199880
199997  499997  81.957653
199998  499998  82.019420
199999  499999  81.597754

[200000 rows x 2 columns]