In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

In [4]:
df_test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
125685,314218,Mercedes-Benz,GL-Class GL 450 4MATIC,2014,83315,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,None reported,Yes
125686,314219,Audi,Q7 55 Prestige,2019,29336,Gasoline,3.0 Liter Turbo,Automatic,White,Black,None reported,NaN
125687,314220,Audi,A6 3.0T Premium Plus,2012,77634,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125688,314221,Audi,Q7 3.0T Premium,2012,112000,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125689,314222,Chevrolet,Tahoe LT,2018,66840,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes

In [5]:
df_train.isna().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(3), object(9)
memory usage: 11.5+ MB

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label = LabelEncoder()

In [10]:
set(df_test['brand']).difference(set(df_train['brand']))

set()

In [11]:
label.fit(df_train['brand'])
df_train['brand'] = label.transform(df_train['brand'])
df_test['brand']  = label.transform(df_test['brand'])

In [12]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(5), object(8)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(4), object(8)
memory usage: 11.5+ MB

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
label = LabelEncoder()

In [15]:
set(df_test['model']).difference(set(df_train['model']))

{'allroad 2.7T'}

In [16]:
all_vals = pd.concat([
    df_train['model'],
    df_test['model']
])

label.fit(all_vals)

LabelEncoder()

In [17]:
df_train['model'] = label.transform(df_train['model'])
df_test['model']  = label.transform(df_test['model'])

In [18]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(6), object(7)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(5), object(7)
memory usage: 11.5+ MB

In [19]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [20]:
set(df_test['fuel_type']).difference(set(df_train['fuel_type']))

set()

In [21]:
df_train['fuel_type'] = pd.to_numeric(
    df_train['fuel_type'],errors = 'coerce')

df_test['fuel_type'] = pd.to_numeric(
    df_test['fuel_type'],errors = 'coerce')
median_hs = df_train['fuel_type'].median()
df_train['fuel_type'] = df_train['fuel_type'].fillna(median_hs)
df_test['fuel_type'] = df_test['fuel_type'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [22]:
label.fit(df_train['fuel_type'])
df_train['fuel_type'] = label.transform(df_train['fuel_type'])
df_test['fuel_type']  = label.transform(df_test['fuel_type'])

In [23]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(7), object(6)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(6), object(6)
memory usage: 11.5+ MB

In [24]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [25]:
set(df_test['engine']).difference(set(df_train['engine']))

{'177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas'}

In [26]:
all_vals = pd.concat([
    df_train['engine'],
    df_test['engine']
])

label.fit(all_vals)

LabelEncoder()

In [27]:
df_train['engine'] = label.transform(df_train['engine'])
df_test['engine']  = label.transform(df_test['engine'])

In [28]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(8), object(5)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(7), object(5)
memory usage: 11.5+ MB

In [29]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [30]:
set(df_test['transmission']).difference(set(df_train['transmission']))

set()

In [31]:
label.fit(df_train['transmission'])
df_train['transmission'] = label.transform(df_train['transmission'])
df_test['transmission']  = label.transform(df_test['transmission'])

In [32]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  int64
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(9), object(4)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  int64
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(8), object(4)
memory usage: 11.5+ MB

In [33]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [34]:
set(df_test['ext_col']).difference(set(df_train['ext_col']))

set()

In [35]:
label.fit(df_train['ext_col'])
df_train['ext_col'] = label.transform(df_train['ext_col'])
df_test['ext_col']  = label.transform(df_test['ext_col'])

In [36]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  int64
 8   ext_col       188533 non-null  int64
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(10), object(3)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  int64
 8   ext_col       125690 non-null  int64
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(9), object(3)
memory usage: 11.5+ MB

In [37]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [38]:
set(df_test['int_col']).difference(set(df_train['int_col']))

set()

In [39]:
label.fit(df_train['int_col'])
df_train['int_col'] = label.transform(df_train['int_col'])
df_test['int_col']  = label.transform(df_test['int_col'])

In [40]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  int64
 8   ext_col       188533 non-null  int64
 9   int_col       188533 non-null  int64
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(11), object(2)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  int64
 8   ext_col       125690 non-null  int64
 9   int_col       125690 non-null  int64
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(10), object(2)
memory usage: 11.5+ MB

In [41]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [42]:
set(df_test['accident']).difference(set(df_train['accident']))

set()

In [43]:
df_train['accident'] = pd.to_numeric(
    df_train['accident'],errors = 'coerce')

df_test['accident'] = pd.to_numeric(
    df_test['accident'],errors = 'coerce')
median_hs = df_train['accident'].median()
df_train['accident'] = df_train['accident'].fillna(median_hs)
df_test['accident'] = df_test['accident'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [44]:
label.fit(df_train['accident'])
df_train['accident'] = label.transform(df_train['accident'])
df_test['accident']  = label.transform(df_test['accident'])

In [45]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  int64
 8   ext_col       188533 non-null  int64
 9   int_col       188533 non-null  int64
 10  accident      188533 non-null  int64
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(12), object(1)
memory usage: 18.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  int64
 8   ext_col       125690 non-null  int64
 9   int_col       125690 non-null  int64
 10  accident      125690 non-null  int64
 11  clean_title   111451 non-null  object
dtypes: int64(11), object(1)
memory usage: 11.5+ MB

In [46]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [47]:
set(df_test['clean_title']).difference(set(df_train['clean_title']))

set()

In [48]:
df_train['clean_title'] = pd.to_numeric(
    df_train['clean_title'],errors = 'coerce')

df_test['clean_title'] = pd.to_numeric(
    df_test['clean_title'],errors = 'coerce')
median_hs = df_train['clean_title'].median()
df_train['clean_title'] = df_train['clean_title'].fillna(median_hs)
df_test['clean_title'] = df_test['clean_title'].fillna(median_hs)

C:\Users\USER\Desktop\ML jupyter\venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [49]:
label.fit(df_train['clean_title'])
df_train['clean_title'] = label.transform(df_train['clean_title'])
df_test['clean_title']  = label.transform(df_test['clean_title'])

In [50]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  int64
 2   model         188533 non-null  int64
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     188533 non-null  int64
 6   engine        188533 non-null  int64
 7   transmission  188533 non-null  int64
 8   ext_col       188533 non-null  int64
 9   int_col       188533 non-null  int64
 10  accident      188533 non-null  int64
 11  clean_title   188533 non-null  int64
 12  price         188533 non-null  int64
dtypes: int64(13)
memory usage: 18.7 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  int64
 2   model         125690 non-null  int64
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     125690 non-null  int64
 6   engine        125690 non-null  int64
 7   transmission  125690 non-null  int64
 8   ext_col       125690 non-null  int64
 9   int_col       125690 non-null  int64
 10  accident      125690 non-null  int64
 11  clean_title   125690 non-null  int64
dtypes: int64(12)
memory usage: 11.5 MB

In [51]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,31,495,2007,213000,0,116,38,312,71,0,0,4200
1,1,28,930,2002,143250,0,367,38,263,10,0,0,4999
2,2,9,1575,2002,136731,0,641,38,38,71,0,0,13900
3,3,16,758,2017,19500,0,864,49,29,14,0,0,45000
4,4,36,1077,2021,7388,0,260,23,29,10,0,0,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,8,604,2017,49000,0,867,49,304,10,0,0,27500
188529,188529,36,206,2018,28600,0,771,31,304,14,0,0,30000
188530,188530,36,223,2021,13650,0,922,23,304,14,0,0,86900
188531,188531,3,1471,2022,13895,0,513,1,82,14,0,0,84900
188532,188532,43,1028,2016,59500,0,365,49,304,14,0,0,28995

In [52]:
df_test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,26,1390,2015,98000,0,326,16,304,10,0,0
1,188534,26,1377,2020,9142,0,788,31,263,14,0,0
2,188535,14,636,2022,28121,0,541,3,304,57,0,0
3,188536,3,182,2016,61258,0,193,39,261,14,0,0
4,188537,3,181,2018,59000,0,365,38,128,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
125685,314218,36,760,2014,83315,0,733,23,29,14,0,0
125686,314219,3,1250,2019,29336,0,511,39,304,14,0,0
125687,314220,3,184,2012,77634,0,674,38,29,14,0,0
125688,314221,3,1246,2012,112000,0,674,38,29,14,0,0
125689,314222,9,1671,2018,66840,0,719,38,263,14,0,0

In [53]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [54]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [55]:
poly = PolynomialFeatures()
model= LinearRegression()

In [56]:
pipe = Pipeline([('poly',poly),('model',model)])

In [57]:
params = {
    'poly__degree':[1, 2, 3, 4],
    'poly__include_bias':[False]
}

In [58]:
from sklearn.model_selection import GridSearchCV

In [59]:
final_model = GridSearchCV(pipe, params , cv = 3, verbose = 2)

In [60]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [61]:
final_model.fit(X_train,y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.0s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.0s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.0s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   0.4s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   0.4s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   0.4s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   2.2s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   2.1s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   2.1s
[CV] END ...........poly__degree=4, poly__include_bias=False; total time=  13.4s
[CV] END ...........poly__degree=4, poly__include_bias=False; total time=  13.4s
[CV] END ...........poly__degree=4, poly__include_bias=False; total time=  13.6s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('poly', PolynomialFeatures()),
                                       ('model', LinearRegression())]),
             param_grid={'poly__degree': [1, 2, 3, 4],
                         'poly__include_bias': [False]},
             verbose=2)

In [62]:
final_model.best_score_

np.float64(0.11698517827216415)

In [63]:
final_model.best_params_

{'poly__degree': 3, 'poly__include_bias': False}

In [64]:
y_pred = final_model.predict(X_test)

In [65]:
df_sub = pd.read_csv('sample_submission.csv')

In [66]:
df_sub['price'] = y_pred

In [67]:
df_sub.to_csv('sub.csv',index = False,index_label= False)

In [68]:
df_sub

            id         price
0       188533  19692.507442
1       188534  83142.745233
2       188535  52869.007491
3       188536  21261.256415
4       188537  26042.881460
...        ...           ...
125685  314218  40521.679146
125686  314219  55504.444898
125687  314220  31969.443133
125688  314221  39060.682370
125689  314222  59760.107723

[125690 rows x 2 columns]