In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,517749,highway,4,0.10,70,daylight,foggy,True,True,afternoon,False,False,2,0.32
517750,517750,rural,4,0.47,35,daylight,rainy,True,True,morning,False,False,1,0.26
517751,517751,urban,4,0.62,25,daylight,foggy,False,False,afternoon,False,True,0,0.19
517752,517752,highway,3,0.63,25,night,clear,True,False,afternoon,True,True,3,0.51
517753,517753,highway,2,0.31,45,dim,rainy,False,True,afternoon,True,True,2,0.22

In [4]:
df_test

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,highway,2,0.34,45,night,clear,True,True,afternoon,True,True,1
1,517755,urban,3,0.04,45,dim,foggy,True,False,afternoon,True,False,0
2,517756,urban,2,0.59,35,dim,clear,True,False,afternoon,True,True,1
3,517757,rural,4,0.95,35,daylight,rainy,False,False,afternoon,False,False,2
4,517758,highway,2,0.86,35,daylight,clear,True,False,evening,False,True,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
172580,690334,rural,2,0.01,45,dim,rainy,False,False,afternoon,True,True,2
172581,690335,rural,1,0.74,70,daylight,foggy,False,True,afternoon,False,False,2
172582,690336,urban,2,0.14,70,dim,clear,False,False,evening,True,True,1
172583,690337,urban,1,0.09,45,daylight,foggy,True,True,morning,False,True,0
172584,690338,highway,1,0.63,35,night,foggy,True,False,evening,False,False,0

In [5]:
df_train.isna().sum()

id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64

In [6]:
df_test.isna().sum()

id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
dtype: int64

In [7]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [8]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  object
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  float64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  object
 5   weather                 517754 non-null  object
 6   road_signs_present      517754 non-null  bool
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(2), int64(3), object(4)
memory usage: 37.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  object
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  float64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  object
 5   weather                 172585 non-null  object
 6   road_signs_present      172585 non-null  bool
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(4), float64(1), int64(3), object(4)
memory usage: 11.2+ MB

In [20]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [21]:
set(df_test['road_type']).difference(set(df_train['road_type']))

set()

In [22]:
df_train['road_type'] = label.fit_transform(df_train['road_type'])
df_test['road_type'] = label.transform(df_test['road_type'])

In [23]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  float64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  object
 5   weather                 517754 non-null  object
 6   road_signs_present      517754 non-null  bool
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(2), int64(4), object(3)
memory usage: 37.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  float64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  object
 5   weather                 172585 non-null  object
 6   road_signs_present      172585 non-null  bool
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(4), float64(1), int64(4), object(3)
memory usage: 11.2+ MB

In [28]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [29]:
set(df_test['curvature']).difference(set(df_train['curvature']))

{0.01,
 0.02,
 0.03,
 0.04,
 0.05,
 0.06,
 0.07,
 0.08,
 0.09,
 0.094,
 0.0968,
 0.1,
 0.11,
 0.12,
 0.13,
 0.14,
 0.1409,
 0.15,
 0.16,
 0.17,
 0.1701,
 0.18,
 0.19,
 0.1902,
 0.1916,
 0.1939,
 0.1949,
 0.1953,
 0.2,
 0.21,
 0.22,
 0.23,
 0.2321,
 0.2324,
 0.2326,
 0.2327,
 0.2337,
 0.2342,
 0.2344,
 0.2353,
 0.2367,
 0.2368,
 0.2373,
 0.2388,
 0.24,
 0.25,
 0.26,
 0.27,
 0.28,
 0.29,
 0.2903,
 0.2906,
 0.2909,
 0.2921,
 0.2927,
 0.2935,
 0.2941,
 0.2967,
 0.2974,
 0.2988,
 0.3,
 0.31,
 0.32,
 0.33,
 0.3301,
 0.3312,
 0.3317,
 0.3321,
 0.3323,
 0.3327,
 0.3328,
 0.3329,
 0.332953,
 0.3334,
 0.3339,
 0.3341,
 0.3342,
 0.3343,
 0.3345,
 0.3351,
 0.3352,
 0.3353,
 0.3359,
 0.3366,
 0.3367,
 0.3373,
 0.3392,
 0.34,
 0.3401,
 0.3412,
 0.3417,
 0.3418,
 0.3421,
 0.343441,
 0.3439,
 0.3465,
 0.3466,
 0.3467,
 0.3468,
 0.3473,
 0.35,
 0.36,
 0.37,
 0.3701,
 0.3729,
 0.3766,
 0.38,
 0.3801,
 0.39,
 0.3901,
 0.3903,
 0.3904,
 0.3905,
 0.3906,
 0.3907,
 0.3909,
 0.3912,
 0.3917,
 0.3918,
 0.3921,
 0.3929,
 0.3941,
 0.3942,
 0.3943,
 0.3965,
 0.4,
 0.41,
 0.42,
 0.4201,
 0.43,
 0.4301,
 0.4314,
 0.4321,
 0.4329,
 0.44,
 0.45,
 0.46,
 0.47,
 0.48,
 0.49,
 0.5,
 0.51,
 0.52,
 0.53,
 0.54,
 0.55,
 0.56,
 0.57,
 0.58,
 0.59,
 0.6,
 0.61,
 0.62,
 0.63,
 0.64,
 0.6411,
 0.6414,
 0.6473,
 0.65,
 0.66,
 0.67,
 0.68,
 0.69,
 0.7,
 0.71,
 0.72,
 0.73,
 0.74,
 0.75,
 0.76,
 0.77,
 0.78,
 0.79,
 0.8,
 0.81,
 0.82,
 0.83,
 0.84,
 0.85,
 0.86,
 0.87,
 0.88,
 0.89,
 0.9,
 0.91,
 0.92,
 0.93,
 0.94,
 0.95,
 0.96,
 0.97,
 0.98,
 0.99}

In [30]:
all_vals = pd.concat([
    df_train['curvature'],
    df_test['curvature']
])

label.fit(all_vals)

LabelEncoder()

In [31]:
df_train['curvature'] = label.fit_transform(df_train['curvature'])
df_test['curvature'] = label.transform(df_test['curvature'])

In [32]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  object
 5   weather                 517754 non-null  object
 6   road_signs_present      517754 non-null  bool
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(1), int64(5), object(3)
memory usage: 37.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  object
 5   weather                 172585 non-null  object
 6   road_signs_present      172585 non-null  bool
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(4), int64(5), object(3)
memory usage: 11.2+ MB

In [33]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [34]:
set(df_test['lighting']).difference(set(df_train['lighting']))

set()

In [35]:
df_train['lighting'] = label.fit_transform(df_train['lighting'])
df_test['lighting'] = label.transform(df_test['lighting'])

In [36]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  object
 6   road_signs_present      517754 non-null  bool
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(1), int64(6), object(2)
memory usage: 37.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  object
 6   road_signs_present      172585 non-null  bool
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(4), int64(6), object(2)
memory usage: 11.2+ MB

In [37]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [38]:
set(df_test['weather']).difference(set(df_train['weather']))

set()

In [39]:
df_train['weather'] = label.fit_transform(df_train['weather'])
df_test['weather'] = label.transform(df_test['weather'])

In [40]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  bool
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(1), int64(7), object(1)
memory usage: 37.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  bool
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(4), int64(7), object(1)
memory usage: 11.2+ MB

In [41]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [42]:
set(df_test['road_signs_present']).difference(set(df_train['road_signs_present']))

set()

In [43]:
df_train['road_signs_present'] = label.fit_transform(df_train['road_signs_present'])
df_test['road_signs_present'] = label.transform(df_test['road_signs_present'])

In [44]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  int64
 7   public_road             517754 non-null  bool
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(3), float64(1), int64(8), object(1)
memory usage: 41.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  int64
 7   public_road             172585 non-null  bool
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(3), int64(8), object(1)
memory usage: 12.3+ MB

In [46]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [48]:
set(df_test['public_road']).difference(set(df_train['public_road']))

set()

In [49]:
df_train['public_road'] = label.fit_transform(df_train['public_road'])
df_test['public_road'] = label.transform(df_test['public_road'])

In [50]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  int64
 7   public_road             517754 non-null  int64
 8   time_of_day             517754 non-null  object
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(2), float64(1), int64(9), object(1)
memory usage: 44.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  int64
 7   public_road             172585 non-null  int64
 8   time_of_day             172585 non-null  object
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(2), int64(9), object(1)
memory usage: 13.5+ MB

In [51]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [52]:
set(df_test['time_of_day']).difference(set(df_train['time_of_day']))

set()

In [53]:
df_train['time_of_day'] = label.fit_transform(df_train['time_of_day'])
df_test['time_of_day'] = label.transform(df_test['time_of_day'])

In [54]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  int64
 7   public_road             517754 non-null  int64
 8   time_of_day             517754 non-null  int64
 9   holiday                 517754 non-null  bool
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(2), float64(1), int64(10)
memory usage: 44.4 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  int64
 7   public_road             172585 non-null  int64
 8   time_of_day             172585 non-null  int64
 9   holiday                 172585 non-null  bool
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(2), int64(10)
memory usage: 13.5 MB

In [55]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [56]:
set(df_test['holiday']).difference(set(df_train['holiday']))

set()

In [57]:
df_train['holiday'] = label.fit_transform(df_train['holiday'])
df_test['holiday'] = label.transform(df_test['holiday'])

In [58]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  int64
 7   public_road             517754 non-null  int64
 8   time_of_day             517754 non-null  int64
 9   holiday                 517754 non-null  int64
 10  school_season           517754 non-null  bool
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: bool(1), float64(1), int64(11)
memory usage: 47.9 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  int64
 7   public_road             172585 non-null  int64
 8   time_of_day             172585 non-null  int64
 9   holiday                 172585 non-null  int64
 10  school_season           172585 non-null  bool
 11  num_reported_accidents  172585 non-null  int64
dtypes: bool(1), int64(11)
memory usage: 14.6 MB

In [59]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [60]:
set(df_test['school_season']).difference(set(df_train['school_season']))

set()

In [61]:
df_train['school_season'] = label.fit_transform(df_train['school_season'])
df_test['school_season'] = label.transform(df_test['school_season'])

In [62]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               517754 non-null  int64
 1   num_lanes               517754 non-null  int64
 2   curvature               517754 non-null  int64
 3   speed_limit             517754 non-null  int64
 4   lighting                517754 non-null  int64
 5   weather                 517754 non-null  int64
 6   road_signs_present      517754 non-null  int64
 7   public_road             517754 non-null  int64
 8   time_of_day             517754 non-null  int64
 9   holiday                 517754 non-null  int64
 10  school_season           517754 non-null  int64
 11  num_reported_accidents  517754 non-null  int64
 12  accident_risk           517754 non-null  float64
dtypes: float64(1), int64(12)
memory usage: 51.4 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172585 entries, 0 to 172584
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   road_type               172585 non-null  int64
 1   num_lanes               172585 non-null  int64
 2   curvature               172585 non-null  int64
 3   speed_limit             172585 non-null  int64
 4   lighting                172585 non-null  int64
 5   weather                 172585 non-null  int64
 6   road_signs_present      172585 non-null  int64
 7   public_road             172585 non-null  int64
 8   time_of_day             172585 non-null  int64
 9   holiday                 172585 non-null  int64
 10  school_season           172585 non-null  int64
 11  num_reported_accidents  172585 non-null  int64
dtypes: int64(12)
memory usage: 15.8 MB

In [64]:
X_train = df_train.drop('accident_risk', axis=1)
y_train = df_train['accident_risk']
X_test = df_test.copy()

In [65]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [66]:
poly = PolynomialFeatures()
model = LinearRegression()

In [67]:
pipe = Pipeline([('poly', poly), ('model', model)])

In [68]:
params = {
    'poly__degree':[1, 2, 3],
    'poly__include_bias':[False]
}

In [69]:
from sklearn.model_selection import GridSearchCV

In [70]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [71]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.1s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.0s
[CV] END ...........poly__degree=1, poly__include_bias=False; total time=   0.0s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.7s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.7s
[CV] END ...........poly__degree=2, poly__include_bias=False; total time=   1.6s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   7.7s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   7.6s
[CV] END ...........poly__degree=3, poly__include_bias=False; total time=   7.3s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('poly', PolynomialFeatures()),
                                       ('model', LinearRegression())]),
             param_grid={'poly__degree': [1, 2, 3],
                         'poly__include_bias': [False]},
             verbose=2)

In [72]:
final_model.best_score_

np.float64(0.8574276827993068)

In [73]:
y_pred = final_model.predict(X_test)

In [74]:
df_sub = pd.read_csv('sample_submission.csv')

In [75]:
df_sub['accident_risk'] = y_pred

In [76]:
df_sub.to_csv('sub.csv',index=False,index_label=False)