In [112]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [113]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [114]:
df_train

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert
...,...,...,...,...,...,...,...,...,...
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,18520,1.0,NaN,6.0,7.0,No,6.0,5.0,Extrovert
18521,18521,7.0,Yes,1.0,1.0,Yes,1.0,NaN,Introvert
18522,18522,NaN,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [115]:
df_test

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,18524,3.0,No,7.0,4.0,No,6.0,NaN
1,18525,NaN,Yes,0.0,0.0,Yes,5.0,1.0
2,18526,3.0,No,5.0,6.0,No,15.0,9.0
3,18527,3.0,No,4.0,4.0,No,5.0,6.0
4,18528,9.0,Yes,1.0,2.0,Yes,1.0,1.0
...,...,...,...,...,...,...,...,...
6170,24694,3.0,No,5.0,5.0,No,9.0,6.0
6171,24695,8.0,Yes,2.0,1.0,Yes,0.0,0.0
6172,24696,2.0,No,4.0,3.0,No,9.0,7.0
6173,24697,3.0,No,4.0,4.0,No,11.0,9.0
6174,24698,NaN,Yes,1.0,1.0,Yes,1.0,0.0

In [116]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         18524 non-null  int64
 1   Time_spent_Alone           17334 non-null  float64
 2   Stage_fear                 16631 non-null  object
 3   Social_event_attendance    17344 non-null  float64
 4   Going_outside              17058 non-null  float64
 5   Drained_after_socializing  17375 non-null  object
 6   Friends_circle_size        17470 non-null  float64
 7   Post_frequency             17260 non-null  float64
 8   Personality                18524 non-null  object
dtypes: float64(5), int64(1), object(3)
memory usage: 1.3+ MB

In [117]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [118]:
df_train.isna().sum()

Time_spent_Alone             1190
Stage_fear                   1893
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing    1149
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64

In [119]:
df_test.isna().sum()

Time_spent_Alone             425
Stage_fear                   598
Social_event_attendance      397
Going_outside                466
Drained_after_socializing    432
Friends_circle_size          350
Post_frequency               408
dtype: int64

In [120]:
df_train['Time_spent_Alone'] = df_train['Time_spent_Alone'].fillna(df_train['Time_spent_Alone'].median())
df_test['Time_spent_Alone'] = df_test['Time_spent_Alone'].fillna(df_test['Time_spent_Alone'].median())

In [121]:
df_train['Stage_fear'].value_counts()

Stage_fear
No     12609
Yes     4022
Name: count, dtype: int64

In [122]:
df_train['Stage_fear'] = df_train['Stage_fear'].apply(lambda x: np.random.choice(a=['Yes', 'No'], p=[0.3, 0.7]) if pd.isna(x) else x)
df_test['Stage_fear'] = df_test['Stage_fear'].apply(lambda x: np.random.choice(a=['Yes', 'No'], p=[0.3, 0.7]) if pd.isna(x) else x)

In [123]:
df_train['Social_event_attendance'] = df_train['Social_event_attendance'].fillna(df_train['Social_event_attendance'].median())
df_test['Social_event_attendance'] = df_test['Social_event_attendance'].fillna(df_test['Social_event_attendance'].median())

In [124]:
df_train['Going_outside'] = df_train['Going_outside'].fillna(df_train['Going_outside'].median())
df_test['Going_outside'] = df_test['Going_outside'].fillna(df_test['Going_outside'].median())

In [125]:
df_train['Drained_after_socializing'].value_counts()

Drained_after_socializing
No     13313
Yes     4062
Name: count, dtype: int64

In [126]:
df_train['Drained_after_socializing'] = df_train['Drained_after_socializing'].apply(lambda x: np.random.choice(a=['No', 'Yes'], p=[0.6, 0.4]) if pd.isna(x) else x)
df_test['Drained_after_socializing'] = df_test['Drained_after_socializing'].apply(lambda x: np.random.choice(a=['No', 'Yes'], p=[0.6, 0.4]) if pd.isna(x) else x)

In [127]:
df_train['Friends_circle_size'] = df_train['Friends_circle_size'].fillna(df_train['Friends_circle_size'].median())
df_test['Friends_circle_size'] = df_test['Friends_circle_size'].fillna(df_test['Friends_circle_size'].median())

In [128]:
df_train['Post_frequency'] = df_train['Post_frequency'].fillna(3.0)
df_test['Post_frequency'] = df_test['Post_frequency'].fillna(3.0)

In [129]:
df_train

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,6.0,Yes,1.0,0.0,No,3.0,0.0,Introvert
3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,1.0,No,4.0,4.0,No,13.0,3.0,Extrovert
...,...,...,...,...,...,...,...,...
18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,1.0,Yes,6.0,7.0,No,6.0,5.0,Extrovert
18521,7.0,Yes,1.0,1.0,Yes,1.0,3.0,Introvert
18522,2.0,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [130]:
df_test

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,3.0,No,7.0,4.0,No,6.0,3.0
1,2.0,Yes,0.0,0.0,Yes,5.0,1.0
2,3.0,No,5.0,6.0,No,15.0,9.0
3,3.0,No,4.0,4.0,No,5.0,6.0
4,9.0,Yes,1.0,2.0,Yes,1.0,1.0
...,...,...,...,...,...,...,...
6170,3.0,No,5.0,5.0,No,9.0,6.0
6171,8.0,Yes,2.0,1.0,Yes,0.0,0.0
6172,2.0,No,4.0,3.0,No,9.0,7.0
6173,3.0,No,4.0,4.0,No,11.0,9.0
6174,2.0,Yes,1.0,1.0,Yes,1.0,0.0

In [131]:
from sklearn.preprocessing import LabelEncoder

In [132]:
for i in df_test.columns:
    if df_train[i].dtype == object:
        label = LabelEncoder()
        df_train[i] = label.fit_transform(df_train[i])
        df_test[i] = label.transform(df_test[i])

In [133]:
X_train = df_train.drop('Personality', axis=1)
y_train = df_train['Personality']
X_test = df_test.copy()

In [1]:
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.pipeline import Pipeline

In [154]:
estimator = DecisionTreeClassifier(max_depth=6, splitter='best', criterion='entropy')

In [155]:
pca = PCA()
model = AdaBoostClassifier(estimator)
pipe = Pipeline([('pca', pca), ('model', model)])

In [156]:
params = {
    'pca__n_components':[1, 2, 3, 4, 5, 6, 7, 8],
    'model__n_estimators':[80, 100, 120, 150],
    'model__learning_rate':[0.01, 0.1, 1, 10]
}

In [157]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [ ]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 128 candidates, totalling 384 fits
[CV] END model__learning_rate=0.01, model__n_estimators=80, pca__n_components=1; total time=   1.9s
[CV] END model__learning_rate=0.01, model__n_estimators=80, pca__n_components=1; total time=   2.0s
[CV] END model__learning_rate=0.01, model__n_estimators=80, pca__n_components=1; total time=   2.0s

In [109]:
final_model.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 6,
 'model__splitter': 'best',
 'pca__n_components': 4}

In [139]:
y_pred = final_model.predict(X_test)

In [140]:
df_sub = pd.read_csv('sample_submission.csv')

In [142]:
df_sub['Personality'] = y_pred

In [143]:
df_sub.to_csv('sub.csv', index=False, index_label=False)